### ISSUE TITLE
Create a website for librepcb.org

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#1]
The webserver is already available (or use github pages)...

**Comment by ubruhin** [comment]
See project https://github.com/LibrePCB/LibrePCB.github.io

**Comment by rnestler** [comment]
Oh nice :smiley: did you use jekyl?

**Comment by ubruhin** [comment]
no, it's made with [hugo](http://gohugo.io/)

**Comment by rnestler** [comment]
Since there is now a website at librepcb.org this can be closed?

**Comment by ubruhin** [comment]
Unfortunately the website is far away from being finished :disappointed: 
It's still very provisional and thus I would leave this issue open until the website is improved.

**Comment by ubruhin** [comment]
This is now replaced by https://github.com/LibrePCB/LibrePCB.github.io/issues/1.
