### ISSUE TITLE
CLI: Use "-v" for "--verbose" instead of "--version"

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#1008]
##### SUMMARY

It's just a detail and I'm not sure if it's even worth to change it since technically this would be a breaking change. But somehow I think it would be more intuitive to use `-v` for `--verbose` instead of `--version` which is currently the case. Especially if we ever want to add several verbosity levels, it's very common to do so by `-vv` and `-vvv`. The short flag for `--version` could be changed to uppercase `-V` since this is also very common.

##### SOLUTION

- Use `-v` for `--verbose`
- Use `-V` for `--version`

However, since it's not really important and actually a breaking change (although probably nobody depends on `-v`), I'd postpone this to v0.2 to comply with semver.

Any opinions welcome :)

**Comment by dbrgn** [comment]
Makes sense.
