### ISSUE TITLE
Black icons almost invisible with dark Qt theme

### ISSUE THREAD

**Issue by The-Compiler** [LibrePCB/LibrePCB#1024]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.2.0-unstable
Git Revision:     3a2fbd534
Build Date:       2022-09-18T15:05:54
Qt Version:       5.15.6 (built against 5.15.6)
CPU Architecture: x86_64
Operating System: Arch Linux
Platform Plugin:  xcb
TLS Library:      OpenSSL 1.1.1q  5 Jul 2022
```

##### SUMMARY
When using the Schematic Editor with a dark Qt theme (e.g. Adwaita-Dark), the black monochrome icons are almost invisible:

##### STEPS TO REPRODUCE
- Set up `qt5ct` and select a theme like Adwaita-Dark

##### EXPECTED RESULTS
- LibrePCB detects that a dark theme is in use, and uses white icons instead, maybe?

##### ACTUAL RESULTS
![image](https://user-images.githubusercontent.com/625793/190978964-080234e5-2bac-4fc8-ad26-d052f1c9139d.png)

##### ADDITIONAL INFORMATION
Looks like those icons are currently PNGs in the repo: https://github.com/LibrePCB/LibrePCB/blob/master/img/actions/add_text.png

Not sure if this should be a bug report or a feature request... Oh, and hoi und merci! :+1:

**Comment by ubruhin** [comment]
Hoi! :smiley: 

Yeah the icons are just theme-independent PNGs, those I have drawn by myself are even very ugly ones :sob:
I agree we should improve this somehow but I didn't find the time yet to do so...

I think one option would be to use [`QIcon::fromTheme()`](https://doc.qt.io/qt-5/qicon.html#fromTheme) and provide different PNGs for some themes. Or maybe there's a more dynamic way to re-color icons on the fly, maybe with SVGs? Anyway, we need to evaluate what would be the way to go.
