### ISSUE TITLE
Usability: Make Project Library Updater a (non-modal) dialog as a hint to window managers

### ISSUE THREAD

**Issue by jwueller** [LibrePCB/LibrePCB#1030]
##### SUMMARY
First of all, I really like this project! It's the only one I tried that didn't make me pull my hair out trying to do a basic PCB for a hobby project.

I'm using a tiling window manager, which uses window type hints to figure out whether to display a window as a floating dialog or a full-sized window.

The Project Library Updater will take up the whole screen, as opposed to many other pop-up windows like the Property Editor.

`xprop` shows the following output for the Project Library Updater window:
```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
```

Here is the relevant output of the Property Editor:
```
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_NORMAL
```

I assume the `_NET_WM_WINDOW_TYPE_DIALOG` hint is the deciding factor, but I'm not certain.

##### SOLUTION
The Project Library Updater is probably semantically a dialog, just like the property editor, which would automatically give the correct hints to the window manager.

**Comment by ubruhin** [comment]
> First of all, I really like this project! It's the only I tried that didn't make me pull my hair out trying to do a basic PCB for a hobby project.

Thanks for this feedback, this is actually one of the main goals of LibrePCB! :smiley: 

> I assume the _NET_WM_WINDOW_TYPE_DIALOG hint is the deciding factor, but I'm not certain.

I can confirm that the project library updater is derived from `QMainWindow`, not `QDialog` like other dialogs. So this might indeed be the reason. Probably there's no reason why it's a `QMainWindow` (at least I can't remember that decision anymore), thus I'd say we should simply change that.
