### ISSUE TITLE
AsyncCopyOperationTest.testEmptySourceDir always fails

### ISSUE THREAD

**Issue by drws** [LibrePCB/LibrePCB#1061]
##### VERSION / OS / ENVIRONMENT
* application version: latest stable (v0.1.7)
* operating system: Arch Linux x86_64
* environment: no special env, updated and otherwise working OS

##### SUMMARY
Since the new build system was introduced in v0.1.6, I haven't been able to build LibrePCB from the AUR package [`librepcb`](https://aur.archlinux.org/packages/librepcb). The test `AsyncCopyOperationTest.testEmptySourceDir` always fails. If I skip `check()`, the package builds and works fine.

##### STEPS TO REPRODUCE
1. try to build [`librepcb`](https://aur.archlinux.org/packages/librepcb)
2. `build()` succeeds, but `check()` doesn't

##### EXPECTED RESULTS
A successfully built package with all tests succeeding.

##### ACTUAL RESULTS
Test `AsyncCopyOperationTest.testEmptySourceDir` always fails.

##### ADDITIONAL INFORMATION
```
[ RUN      ] AsyncCopyOperationTest.testEmptySourceDir
build/librepcb/src/librepcb-0.1.7/tests/unittests/core/fileio/asynccopyoperationtest.cpp:124: Failure
Expected equality of these values:
  mSignalStarted
    Which is: 0
  1
build/librepcb/src/librepcb-0.1.7/tests/unittests/core/fileio/asynccopyoperationtest.cpp:125: Failure
Expected: (mSignalProgressStatus.count()) >= (1), actual: 0 vs 1
build/librepcb/src/librepcb-0.1.7/tests/unittests/core/fileio/asynccopyoperationtest.cpp:126: Failure
Expected: (mSignalProgressPercent.count()) >= (1), actual: 0 vs 1
build/librepcb/src/librepcb-0.1.7/tests/unittests/core/fileio/asynccopyoperationtest.cpp:127: Failure
Expected equality of these values:
  mSignalSucceeded
    Which is: 0
  1
build/librepcb/src/librepcb-0.1.7/tests/unittests/core/fileio/asynccopyoperationtest.cpp:129: Failure
Expected equality of these values:
  mSignalFinished
    Which is: 0
  1
[  FAILED  ] AsyncCopyOperationTest.testEmptySourceDir (1 ms)
```

**Comment by frankenstein91** [comment]
I see this problem too.
Tested the install today.
