### ISSUE TITLE
Arduino Board Library - Boards wont place in board editor

### ISSUE THREAD

**Issue by crunchysteve** [LibrePCB/LibrePCB#1064]
The library seems to have no artwork to place on the board.

LibrePCB Version: 0.1.7
Git Revision:     ba553c6fb
Build Date:       2022-10-03T08:32:18
Qt Version:       5.15.6 (built against 5.15.6)
CPU Architecture: x86_64
Operating System: macOS 13.0
Platform Plugin:  cocoa
TLS Library:      Secure Transport, macOS 13.0

**Comment by ubruhin** [comment]
This is not a problem of the application, thus closing this issue. It is impossible to provide complete libraries for everything so you need to create the missing elements by yourself. It is very simple, see instructions [here](https://librepcb.org/docs/quickstart/create-library-elements/). See also the FAQ [I can’t find XYZ in the libraries, where is it?](https://librepcb.org/faq/#where-is-library-element).
