### ISSUE TITLE
Gerber generation missing from menu

### ISSUE THREAD

**Issue by abulka** [LibrePCB/LibrePCB#1069]
Gerber generation missing from menu

> The manual says this is possible: Gerber/Excellon Open File › Production Data › Generate Fabrication Data or press F10 . Then choose the settings of the Gerber/Excellon export.

```
LibrePCB Version: 0.1.7
Git Revision:     ba553c6fb
Build Date:       2022-10-03T08:32:18
Qt Version:       5.15.6 (built against 5.15.6)
CPU Architecture: x86_64
Operating System: macOS 13.0
Platform Plugin:  cocoa
TLS Library:      Secure Transport, macOS 13.0
```
Did I miss an installation step or something?

![Screenshot 2022-11-29 at 10 34 54 am](https://user-images.githubusercontent.com/11467530/204402942-9acaf5e6-da4e-45c8-a767-7a47124a0642.png)

**Comment by ubruhin** [comment]
The menu item exists only in the board editor, not in the schematic editor. So probable the focus was on the wrong window.

**Comment by abulka** [comment]
Oh, I see - thanks!
