### ISSUE TITLE
Board editor: no option to rename an existing board

### ISSUE THREAD

**Issue by hooperbloob** [LibrePCB/LibrePCB#1095]
##### VERSION / OS / ENVIRONMENT
LibrePCB Version: 0.1.7
Git Revision:     ba553c6fb
Build Date:       2022-10-03T08:32:18
Qt Version:       5.15.6 (built against 5.15.6)
CPU Architecture: x86_64
Operating System: macOS 12.6
Platform Plugin:  cocoa
TLS Library:      Secure Transport, macOS 12.6

##### SUMMARY
While you can rename a schematic sheet after creation there is no option to rename an existing board.

**Comment by ubruhin** [comment]
True, currently the only way would be to edit the `board.lp` file manually :see_no_evil:
