### ISSUE TITLE
DRC: Circular courtyards all placed at board origin

### ISSUE THREAD

**Issue by Angelsen** [LibrePCB/LibrePCB#1115]
When running the DRC it seems like the courtyards are all placed at orgio -> they collide with each other. 

LibrePCB Version: 0.2.0-unstable
Git Revision:     8da666215
Build Date:       2023-02-27T08:24:12
Qt Version:       5.15.8 (built against 5.15.8)
CPU Architecture: x86_64
Operating System: Manjaro Linux
Platform Plugin:  xcb
TLS Library:      OpenSSL 3.0.8 7 Feb 2023

![image](https://user-images.githubusercontent.com/15813633/221678764-4e4b8aff-c624-466a-aaa5-944096bdf23f.png)

**Comment by ubruhin** [comment]
Thanks for reporting! Was able to reproduce it, seems to affect only circles (not polygons).
