### ISSUE TITLE
Library editor: place and size multiple items simultaneously

### ISSUE THREAD

**Issue by kotchin** [LibrePCB/LibrePCB#1169]
First of all, thank you for making LibrePCB, I enjoy using it.

I have been looking into the documentation, searching through options and digging into issues but have not been able to find anything relating to editing multiple items together, in the library editor. I am assuming this would fall under "small feature" request. If this feature does exist, please let me know how it works and ignore this feature request and apologies for the bother.

##### SUMMARY
What I mean by editing multiple items, is selecting multiple items (such as SMT pads in library editor) and being able to modify one or multiple properties (e.g. size, position, rotation) while others remain untouched. 

This is a convenience feature and would allow for rapid property editing of multiple items simultaneously. One example is, if one wants to align 10 SMT pads along some specific horizontal line which doesn't align with the grid, one has to manually edit the coordinate of all items, one by one.

##### SOLUTION
How this would work in practice is that when opening the properties for multiple items, the exact values for size, position, rotation etc, would be something non-numeric, such as "multiple", or "...". Only editing any such field with a specific value would assign that same value to all selected items, whereas all other fields would remain unchanged.

Please find below, the kind of library editor package I was working with when I was thinking of this feature :)

![librepcb_feature_req](https://github.com/LibrePCB/LibrePCB/assets/6894486/5bc16ca6-0d07-4cb4-9042-dc925aa66f89)

**Comment by ubruhin** [comment]
> First of all, thank you for making LibrePCB, I enjoy using it.

Nice to hear, thanks! :)

Regarding your feature request: I totally agree this would be very useful. I think this is something to look at after the next major release :+1:

**Comment by ubruhin** [comment]
FYI, the next release will contain two features related to this issue:
- #1412
- #1432

Keeping this issue open anyway since there's no property editor for multiple selected objects yet.

**Comment by kotchin** [comment]
This looks like it addresses the initial post adequately! Thank you for your extensive work. Much appreciated!
