### ISSUE TITLE
Allow missing, optional, schematic symbols to be placed for existing components

### ISSUE THREAD

**Issue by pruby** [LibrePCB/LibrePCB#1191]
##### SUMMARY
When a component has been added to a schematic, which consists of more than one symbol, any optional symbols not initially placed cannot later be added without removing and replacing the component. The current limitation forces a workflow of placing all the optional components, and keeping them aside somewhere for later.

##### SOLUTION
Provide a tool or right-click menu option which allows the user to resume placing optional symbols for an already-added component.

**Comment by ubruhin** [comment]
Hi @pruby, thanks for reporting the issue you experience with LibrePCB! :+1:

This particular issue has already been reported in #448, thus I'll close this one.
