### ISSUE TITLE
Add "Contribution" section to readme

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#12]
List some different ways how to contribute to LibrePCB, for example:
- coding: fix issues (starting with issues labeled with "easy")
- design/coding: create a website? design icons?
- donate: [Gratipay](https://gratipay.com/)?
- donate: PayPal?
- donate: Bitcoin?
- other ways to contribute?

also an IRC channel would be nice...

**Comment by rnestler** [comment]
You probably want to also crate a file [`CONTRIBUTING.md`](https://github.com/blog/1184-contributing-guidelines) with contributing guidelines.
