### ISSUE TITLE
Build broken on branch master

### ISSUE THREAD

**Issue by asanza** [LibrePCB/LibrePCB#124]
trying to build the master branch returns following error:

Cannot find file: LibrePCB/3rdparty/hoedown/hoedown.pro

perhaps was not include in the commit?

Regards,

**Comment by asanza** [comment]
Forget it. 

I forgot to pull the submodules... :)

**Comment by ubruhin** [comment]
Hi,
> I forgot to pull the submodules... :)

Yeah that's something which is not yet mentioned in the Readme ;) I will add this some day...
