### ISSUE TITLE
AppImage is not launching under Wayland

### ISSUE THREAD

**Issue by bubelov** [LibrePCB/LibrePCB#1242]
```
./librepcb-1.0.0-linux-x86_64.AppImage
```

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```

It was an Arch machine with QT5 installed. Please let me know if you need more data or logs.

I also tried AUR but there is something wrong with the sigs:

```
==> Verifying source file signatures with gpg...
    librepcb-1.0.0-source.zip ... FAILED (unknown public key 7EF3061F5C8D5E25)
==> ERROR: One or more PGP signatures could no
```

**Comment by bubelov** [comment]
```
pacman --query --info xorg-xwayland
```

```
Name            : xorg-xwayland
Version         : 23.2.1-1
Description     : run X clients under wayland
Architecture    : x86_64
URL             : https://xorg.freedesktop.org
Licenses        : custom
Groups          : xorg
Provides        : xorg-server-xwayland
Depends On      : nettle  libepoxy  systemd-libs  libxfont2  pixman  xorg-server-common  libxcvt  mesa  libglvnd  libxau  wayland  libdrm  libtirpc  libxshmfence  glibc
Optional Deps   : None
Required By     : mutter
Optional For    : None
Conflicts With  : xorg-server-xwayland
Replaces        : xorg-server-xwayland
Installed Size  : 2.23 MiB
Packager        : Andreas Radke <andyrtr@archlinux.org>
Build Date      : Wed 20 Sep 2023 09:08:57 PM +07
Install Date    : Fri 22 Sep 2023 09:20:06 AM +07
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

`xorg-xwayland` appears to be a core dep of GNOME, so it's already installed. I'll try to import that key and test the AUR installation.

**Comment by bubelov** [comment]
It looks like some tests are failing:

```
[----------] Global test environment tear-down
[==========] 2134 tests from 120 test suites ran. (25717 ms total)
[  PASSED  ] 2133 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GraphicsExportDialogTest.testCopyToClipboard

 1 FAILED TEST
==> ERROR: A failure occurred in check().
    Aborting...
```

```
[ RUN      ] GraphicsExportDialogTest.testCopyToClipboard
/home/igor/projects/aur/librepcb/src/librepcb-1.0.0/tests/unittests/editor/dialogs/graphicsexportdialogtest.cpp:271: Failure
Value of: (static_cast<QApplication *>(QCoreApplication::instance()))->clipboard()->image().isNull()
  Actual: true
Expected: false

[  FAILED  ] GraphicsExportDialogTest.testCopyToClipboard (133 ms)
```

```
[ RUN      ] OccModelTest.testLoadStepInvalid
**** ERR StepFile : Undefined Parsing: Line 2: Incorrect syntax: unexpected end of file, expecting STEP    ****
[       OK ] OccModelTest.testLoadStepInvalid (0 ms)
```

Clipboard issues can also be related to Wayland, but I'm not sure. I heard it's very different from X under the hood, so I guess it's possible that QT5 is struggling to provide a good abstraction.

**Comment by ubruhin** [comment]
> Clipboard issues can also be related to Wayland, but I'm not sure. 

Yeah that might be the case.

Btw, maybe it helps to know some more details about your system, e.g. are you actually using Gnome or some other desktop environment?

At least on my Arch based system the AppImage works fine. Maybe @dbrgn could also check if the AppImage works(?).

**Comment by bubelov** [comment]
> Btw, maybe it helps to know some more details about your system, e.g. are you actually using Gnome or some other desktop environment?

I have two almost identical Arch machines, both running the latest GNOME (44.5) under Wayland.

- Dell XPS 13 9380 (Intel i7)
- PC (AMD Ryzen 7 5800X, AMD Radeon RX 6600 XT)

The issues mentioned above are related to XPS laptop. I just tried launching AppImage on my desktop PC and it seems to be working fine:

![Screenshot from 2023-10-03 10-56-27](https://github.com/LibrePCB/LibrePCB/assets/1189245/bbaa8915-6789-44cd-81fa-aecafe92b2e1)

There is nothing remarkable about that laptop, except:

- It has a weaker integrated GPU and it's from Intel, not AMD. I'm under impression that AMD plays nicer with Linux, but it's just a guess
- It uses fractional scaling (13" + 4K is a very odd combo and it doesn't work that well with either 200% or 300% scaling)

Is there a way to enable verbose logging or getting a crash report?

**Comment by ubruhin** [comment]
Hm ok, interesting. Just an idea:

> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

The first line is normal on Wayland and is not causing any crash (as you can see in the logs of your desktop PC). But the second line sounds like Qt tries to load the Wayland plugin anyway, although the xcb plugin shall be loaded. This brings me to the question if `XDG_SESSION_TYPE=wayland` is somehow set globally? Could you check if there's any effect when explicitly starting the AppImage with `XDG_SESSION_TYPE=xcb`?

    XDG_SESSION_TYPE=xcb ./librepcb-1.0.0-linux-x86_64.AppImage

> Is there a way to enable verbose logging or getting a crash report?

I'm not aware of any. It looks like the application is terminated by Qt before any LibrePCB code is executed.

**Comment by bubelov** [comment]
@ubruhin your suggestion was spot-on, in fact I had an env variable instructing QT to use a Wayland backend, since Telegram and all the other QT apps look blurry if not forced to use this backend.

Shall we close this issue? I can't find any other issue related to Wayland, so I'm not sure if it should be closed or renamed to "Add Wayland backend support" or something.

Are there any plans to add Wayland support? Would this issue auto-resolve with QT6 migration?

**Comment by ubruhin** [comment]
Nice! I just opened #1249 for providing Wayland support so I'll close this issue.

> Would this issue auto-resolve with QT6 migration?

Qt6 _might_ help, but I don't think so. At least some of the issues are not Qt related.
