### ISSUE TITLE
UI Rework suggestion

### ISSUE THREAD

**Issue by GravisZro** [LibrePCB/LibrePCB#1253]
##### SUMMARY
Since the UI is apparently being reworked, I suggest a design based on the Qt Creator GUI design.  The mock up doesn't cover everything about the GUI but I think it's a solid basis for turning the multiple windows GUI into a single window GUI.

![2023-10-06_12-50](https://github.com/LibrePCB/LibrePCB/assets/670534/4a5e9403-127f-484e-ab9c-434de0aff1ff)

**Comment by ubruhin** [comment]
Thanks for this suggestion! Interestingly your mockup looks basically identical to mine :smiley: 

![image](https://github.com/LibrePCB/LibrePCB/assets/5374821/2d37039f-d291-481c-aa76-392c36a6eeb7)

**Comment by GravisZro** [comment]
Well... it looks like my work here is done.
