### ISSUE TITLE
Where to store test data files for unit tests?

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#126]
Some unit tests require test data files to execute their tests (for example zipped libraries, extracted libraries, projects, whatever, ...). But where to store such files?
#### In a subdirectory like "tests/data/" in this repository

Simple, but I don't like to commit many/large/binary files into a repository which contains source code.
#### Create a new repository like "librepcb-test-data" and add it as a submodule to this repository

Better in my opinion ;)

**Comment by 0xB767B** [comment]
Seperating tests and test data seems not to be a good option to me. How about a new repository for tests and test data?

**Comment by dbrgn** [comment]
I agree with @0xB767B that tests and data belong together. On the other hand, the data repo could be added as a submodule, then the reference to a specific version of the test data *is* bundled together with the tests :)
