### ISSUE TITLE
Circular outline

### ISSUE THREAD

**Issue by eto-** [LibrePCB/LibrePCB#1270]
##### SUMMARY

I need a circular PCB: in the documentation it seems to be possible but I did not find a way.
For now, I wrote a small script that add to the boad.lp a regular polygon with 20 edges that approximates the circle well enough.

**Comment by dbrgn** [comment]
@eto- you mean rounded corners, or an actual circle?

Both should be possible: If you double-click the polygon, you can set the angle. Example:

![screenshot-20231120-175414](https://github.com/LibrePCB/LibrePCB/assets/105168/b5c8b167-ba43-411d-85be-3522bd6c4578)

The UI for this is still missing. See  #1263 for the tracking issue about such a UI feature.

**Comment by eto-** [comment]
Ok, thanks this is useful.
I needed a fully circular PCB, and I didn't think to put 2 parallel lines with 180° angle.
But it works.
