### ISSUE TITLE
You got mail!

### ISSUE THREAD

**Issue by qcGVkzEG** [LibrePCB/LibrePCB#1281]
Hi! Here's a postcard for y'all from the past:

![front](https://github.com/LibrePCB/LibrePCB/assets/17107395/a99f573c-31d8-411d-9a5e-cc91310b77c0)
![back](https://github.com/LibrePCB/LibrePCB/assets/17107395/008a19fa-39a4-4262-8832-394394a66539)

If you'd like to pick up the physical card, go to any CCC event that has a ChaosPost office.

**Comment by dbrgn** [comment]
Wohoo, it finally arrived 🎉 Thanks C3Post 🙂

**Comment by ubruhin** [comment]
Haha very nice, thank you! :smiley: 

So as the mail is delivered, I suspect the issue can be closed :thinking:  :see_no_evil:
