### ISSUE TITLE
Library/Symbol Editor: allow dotted or dashed lines for graphical elements

### ISSUE THREAD

**Issue by Schorsch99** [LibrePCB/LibrePCB#1295]
##### SUMMARY
Some symbols just look better if different line styles can be used for the graphical elements, for example a relay symbol:

![grafik](https://github.com/LibrePCB/LibrePCB/assets/27017311/4aa4cc2c-5e3c-472e-9426-07230fdfbdda)

##### SOLUTION
Please add selection option in symbol editor not only for line width, but also for line style

**Comment by ubruhin** [comment]
Duplicate of #812, thus closing this one.
