### ISSUE TITLE
Add Repology badge to README

### ISSUE THREAD

**Issue by luzpaz** [LibrePCB/LibrePCB#1299]
https://repology.org displays what version of a specific software is available in the packaging ecosystem. Can be helpful to track if any downstream repos need updating.

### Large badge 

[![Packaging status](https://repology.org/badge/vertical-allrepos/librepcb.svg?columns=3&header=LibrePCB)](https://repology.org/project/librepcb/versions)

### Small badge

[![Packaging status](https://repology.org/badge/tiny-repos/librepcb.svg)](https://repology.org/project/librepcb/versions)

**Comment by ubruhin** [comment]
I worry a little bit whether the large badge would be too "noisy" in the README or not :thinking: But it might be useful indeed, so I think I'd accept a pull request. I'd probably go with the large badge then as it provides the overview directly.

**Comment by luzpaz** [comment]
Where would you want the badge placed specifically in the README ?

**Comment by ubruhin** [comment]
I'd put it just below the current badges on a new line, separated the same was as the current two badge groups.

**Comment by luzpaz** [comment]
> I worry a little bit whether the large badge would be too "noisy" in the README or not 

Note: If this becomes too noisy, you can always hide the badge within a collapsed div like so:

<details>
<summary>Expand to view downstream package repo status</summary>

[![Packaging status](https://repology.org/badge/vertical-allrepos/librepcb.svg?columns=3&header=LibrePCB)](https://repology.org/project/librepcb/versions)

</details>
