### ISSUE TITLE
LibrePCB-1.0.0 does not support OpenCascade 7.8.0

### ISSUE THREAD

**Issue by thierry-FreeBSD** [LibrePCB/LibrePCB#1315]
##### VERSION / OS / ENVIRONMENT
Tested on FreeBSD, but it will give the same result on any OS.

```
LibrePCB Version: 1.0.0
```

##### SUMMARY
Compilation fails with the message:
```
ld: error: unable to find library -lTKXDESTEP
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
*** Error code 1
```

##### STEPS TO REPRODUCE
- install OpenCascade 7.8.0
- try to build LibrePCB

##### EXPECTED RESULTS
Build succeeded!

##### ACTUAL RESULTS
See the reported error.

##### ADDITIONAL INFORMATION
N/A

**Comment by ubruhin** [comment]
Arghh seems they suddenly reorganized library modules :sob: If I understand correctly, `TKXDESTEP` was renamed to `TKDESTEP` but maybe that's not the only change...

See https://dev.opencascade.org/doc/overview/html/occt__upgrade.html#upgrade_occt780

**Comment by ubruhin** [comment]
@thierry-FreeBSD This should be fixed in the next release. If you already want to try it with LibrePCB 1.0.0, just apply the patch https://github.com/LibrePCB/LibrePCB/pull/1329.

(not yet verified if this also works at runtime, will be tested later)

**Comment by ubruhin** [comment]
I have now tested with OCCT 7.8.0 and although it links without errors, LibrePCB crashes when opening a STEP file :sob: Seems this is a bug in OCCT 7.8.0: https://tracker.dev.opencascade.org/view.php?id=33631

I think I'll "blacklist" OCCT 7.8.0 in CMake (throwing an error if this version is used) and we'll need to wait for the next release.
