### ISSUE TITLE
Docker: Simplify X11 Setup

### ISSUE THREAD

**Issue by 0xB767B** [LibrePCB/LibrePCB#132]
It seems as the ugly xauth/sed hack in build_container.sh can be simplified using xhost +local:

See: https://github.com/0xB767B/dockerfiles/tree/master/qtcreator

It might as well not be the safest solution, but at least more understandable what the script is doing.

I'll try it on LibrePCB at some point.

**Comment by ubruhin** [comment]
> I'll try it on LibrePCB at some point.

:+1:

**Comment by ubruhin** [comment]
See also #152.

**Comment by ubruhin** [comment]
FYI, the Dockerfile will be removed in #647.
