### ISSUE TITLE
Make PPA for Trusty 14.04

### ISSUE THREAD

**Issue by Symbian9** [LibrePCB/LibrePCB#139]
Please, make PPA on Launchpad or on openSUSE Builts services, that would provide DEB's as "nightly builds" for testing.

**Comment by dbrgn** [comment]
Yeah, that would actually be pretty cool.

I might give the openSUSE build service a try next Monday, what do you think @ubruhin?

**Comment by ubruhin** [comment]
I have already [played around](https://build.opensuse.org/package/show/home:ubruhin/librepcb) with OBS some time ago, but I didn't really understand how it works ;)

> I might give the openSUSE build service a try next Monday, what do you think @ubruhin?

Of course, that would be great!

BTW, I have also played around with [AppImage](http://appimage.org/) on the branch [deploy_appimage](https://github.com/LibrePCB/LibrePCB/tree/deploy_appimage) to upload nightly build packages to [Bintray](https://bintray.com/librepcb)...

**Comment by dbrgn** [comment]
If we would be able to use Gitlab CI, we could build all images ourselves using Docker base images... :grin:

**Comment by probonopd** [comment]
> BTW, I have also played around with AppImage on the branch deploy_appimage to upload nightly build packages to Bintray...

Works well for me on xubuntu-16.04-desktop-amd64.iso. Thanks @ubruhin

**Comment by ubruhin** [comment]
> If we would be able to use Gitlab CI, we could build all images ourselves using Docker base images...

Gitlab CI is awesome, but couldn't we also use Docker on Travis-CI?

> Works well for me on xubuntu-16.04-desktop-amd64.iso.

Great to hear! Unfortunately there are still some issues, I have documented them in #140. Maybe you have some useful tips for us ;)

**Comment by dbrgn** [comment]
> Gitlab CI is awesome, but couldn't we also use Docker on Travis-CI?

I don't think so. Travis uses Docker themselves, and for Docker-in-Docker you need a special privileged mode on the host Docker.

**Comment by probonopd** [comment]
It is possible to use custom Docker containers on Travis CI. I use it to build some AppImages.

**Comment by dbrgn** [comment]
Whoa, really? Do you have a link to the documentation?

**Comment by probonopd** [comment]
https://github.com/probonopd/AppImageKit/wiki/Docker-Hub-Travis-CI-Workflow

**Comment by ubruhin** [comment]
Since in the meantime we have stable releases available with different deployment methods, and Ubuntu 14.04 is end of life anyway, I think this issue is no longer relevant ;)

**Comment by probonopd** [comment]
Indeed xenial now is the oldest still-supported LTS release, and there is an AppImage. So, thank you very mcuh :+1:
