### ISSUE TITLE
Cannot place standard component on board

### ISSUE THREAD

**Issue by DanielSWolf** [LibrePCB/LibrePCB#1399]
##### VERSION / OS / ENVIRONMENT

LibrePCB Version: 1.1.0
Git Revision:     18a3d4589
Build Date:       2024-04-03T09:45:54
Build Author:     LibrePCB CI
Qt Version:       5.15.2 (built against 5.15.2)
CPU Architecture: x86_64
Operating System: Windows 10 Version 2009
Platform Plugin:  windows
TLS Library:      OpenSSL 1.1.1v  1 Aug 2023
OCC Library:      OCCT 7.7.2

##### SUMMARY

I created a simple schematic containing only standard library components, but when trying to place them, the Place Devices panel gives me this error:

> No device or package for the selected component found in the library! Please add a suitable device and package to your workspace library.

##### STEPS TO REPRODUCE

1. Create a new workspace
2. Install the three default LibrePCB libraries
3. Create a schematic containing one "Soldered Wire Connector 1x03" and one "Screw Terminal 1x02".
4. Try to add both to the board.

##### EXPECTED RESULTS

Both the wire connector and the screw terminal can be added. I'm assuming that the components available from the *Add Component* dialog are those from the three default libraries I just installed.

##### ACTUAL RESULTS

The wire connector can be added fine, but the screw terminal cannot be added, showing me the above error message instead.

**Comment by DanielSWolf** [comment]
Thanks for the quick reply! As a new user, designing a new library just for a screw terminal seems a bit excessive to me. In the end, all I want are two connections with 5,08 mm space between. So I was hoping the component would come with a simple default implementation that's good enough for this purpose.

Can you recommend an approach?

**Comment by ubruhin** [comment]
> As a new user, designing a new library just for a screw terminal seems a bit excessive to me.

I understand this, but in the end with LibrePCB it's really easy - especially when you start by copying an existing package, so I'd suggest to do it this way. For example in your own local library, just create a new package by copying an existing one:

![image](https://github.com/LibrePCB/LibrePCB/assets/5374821/bae675aa-0c40-4224-a10a-3195f98bace8)

Then choose e.g. the "Generic Pin Socket 2.54mm 1x02" package and adjust it accordingly. Then creating a new device for it is really really simple. It sounds complicated in the beginning but it's worth to learn it, afterwards you'll see it's really easy and doesn't take a lot of time.

Of course I hope soon our libraries will contain screw terminals, but as mentioned it's totally impossible to provide all the millions of parts. So in the end, the ability to create your own library elements is very valuable (no matter which EDA tool you use).

**Comment by dbrgn** [comment]
I have some simple screw terminal packages in my personal library: https://github.com/dbrgn/Brgn.lplib

- Aliexpress Screw Terminal 2.54mm 1x02
- Aliexpress Screw Terminal 2.54mm 1x03
- AMPHENOL_TC0223620000G

The one by Amphenol could work for you. You can add the library, copy over the packages to an empty library that you create for yourself, and then remove my library again.

Note that GitHub is not the right place to discuss this. Instead, you could open a question at https://librepcb.discourse.group/ in the "Libraries" category. Maybe other users have already created screw terminal packages as well.

**Comment by ubruhin** [comment]
Good points, thanks @dbrgn :+1:

> You can add the library, copy over the packages to an empty library that you create for yourself, and then remove my library again.

To install the library, just use the "Download Manually" tab in the library manager and insert this URL: https://github.com/dbrgn/Brgn.lplib/archive/refs/heads/master.zip. Whether to copy the elements to you own library or not is up to you, you could simply keep dbrgn's library installed.

**Comment by DanielSWolf** [comment]
Thank you both! The Amphenol screw terminal worked perfectly.

> Note that GitHub is not the right place to discuss this. Instead, you could open a question at https://librepcb.discourse.group/ in the "Libraries" category. Maybe other users have already created screw terminal packages as well.

Thanks for pointing this out! I only created this issue thinking this was a bug. Next time I need a part, I'll be sure to visit there.

**Comment by xotho** [comment]
I confirm and I also suggest to import LIBS from OLD CADSOFT, you will many parts "already ready"...

take care,
X!
