### ISSUE TITLE
[question] import jpeg / svg ?

### ISSUE THREAD

**Issue by Fr-Dae** [LibrePCB/LibrePCB#1403]
Hello/Bonjour, 
I am looking for a solution to import a jpeg or svg on librepcb, 
I would like to use a photo of a PCB that I need to clone on librepcb and place component on it

but i don't know how to do 
if anyone have information 
thank you =)

**Comment by ubruhin** [comment]
Hi,
That's not supported yet but it's planned to implement some day. The only import tool currently is for DXF so maybe you could convert your image somehow to DXF.

And please note that neither this issue tracker nor the Telegram dev chat is for support questions, thus closing the issue. Please use the forum instead, see https://librepcb.org/help/.
