### ISSUE TITLE
Icon pack workflow

### ISSUE THREAD

**Issue by ikcom** [LibrePCB/LibrePCB#1410]
# SUMMARY

Following your [suggestion](https://github.com/LibrePCB/LibrePCB/blob/master/CONTRIBUTING.md#notes) to ask feedback before contributing, I wanted to know if there's need to build an icon design workflow since I noticed a few past issues with licensing.

Here's a little sample I tested:
![image](https://github.com/LibrePCB/LibrePCB/assets/76174793/2dbdc0ef-59ee-4020-b934-e8ee955603be)

![image](https://github.com/LibrePCB/LibrePCB/assets/76174793/c93954af-8987-4756-b472-7a7758ca2894)

# SOLUTION

Use the workflow [bootstrap icons](https://github.com/twbs/icons?tab=readme-ov-file#adding-svgs) use with Figma, but perhaps rewrite the rasterization process in python since it is already a development dependency.
Although this takes more effort it will make for a much better user experience

**Comment by ubruhin** [comment]
Hi,
The icons look not bad (in fact there was already some discussion about using bootstrap icons) but somehow I don't understand exactly your suggestion about what we should do (workflow? Figma? rasterization process?). Would be nice if you could explain it in more detail :wink:

Note that there is also some work/experiments ongoing with a completely new GUI (see https://github.com/LibrePCB/LibrePCB/issues/1253 for mockups) which would eliminate many colored icons as it would heavily rely on monochrome icons. Thus at the moment it makes not much sense to spend a lot of effort into improving the current icons. But still some thoughts could be valuable for the new GUI of course.

**Comment by ubruhin** [comment]
Yes Qt can load SVG directly. Though I didn't know Figma, at the moment I don't see how Figma could help us so I'll close this issue for now. Feel free to reopen if you disagree ;-)
