### ISSUE TITLE
PROPERTIES filling about of Resistors, Capacitors, Inductors .

### ISSUE THREAD

**Issue by xotho** [LibrePCB/LibrePCB#1428]
Why not adding the possibility to have a RANGE instead of just a specific value for the component ?

This could help a lot when optimizing BOMs of different projects when a stock is present and a products have to be quickly advanced.

![image](https://github.com/user-attachments/assets/548d4090-d5b7-4253-bb6f-71606e4d18a6)

A= add a field (SINGLE VALUE / RANGE)
B= variant field VALUE / (VALUE MIN and VALUE MAX)
Take care.
X!

**Comment by ubruhin** [comment]
I think this is overcomplicated, implementing it would make the application even more complicated without much advantages. Such values could even confuse assembly houses so I don't want to propose users specifying ranges of values.

In addition, if you really want it, there are already 2 ways available:
- Either [specify alternative parts](https://librepcb.org/docs/user-manual/project-editor/assembly-data/#alternative-parts), e.g. add both values "100 nF" and "220 nF". Not a range, I know, but advantage is that even assembly houses should handle it correctly.
- Or just use **string** attribute and write "100..220nF". But if you send the design to an assembly house I would not do this.

Closing as not intended to implement - sorry.
