### ISSUE TITLE
check pointer

### ISSUE THREAD

**Issue by maddin200** [LibrePCB/LibrePCB#1446]
File:
/libs/librepcb/editor/project/schematiceditor/graphicsitems/sgi_netlabel.cpp line 131
Code:
 else {
    // draw filled rect
    painter->setPen(Qt::NoPen);
    painter->setBrush(
        QBrush(mNetLabelLayer->getColor(highlight), Qt::Dense5Pattern)); // <-- check pointer mNetLabelLayer (maybe invalid)
    painter->drawRect(mBoundingRect);
  }

**Comment by ubruhin** [comment]
Thanks. It's not a real problem since in practice `mNetLabelLayer` is always valid. But I'll improve it anyway.

Was it reported by a compiler? Any other warnings or is this the only one?
