### ISSUE TITLE
ERROR: Could not add component

### ISSUE THREAD

**Issue by szg0000** [LibrePCB/LibrePCB#148]
If I want to add a component an error message comes up:

![librepcb_add_component_error](https://cloud.githubusercontent.com/assets/18247040/22883917/a460f632-f1f2-11e6-9734-5c50c51916f3.png)

**Comment by dbrgn** [comment]
Did you clone and use the [demo workspace](https://github.com/LibrePCB/demo-workspace)?

**Comment by szg0000** [comment]
With demo workspace it works, but I want to use LibrePCB without demo workspace.

**Comment by dbrgn** [comment]
I think right now LibrePCB does not ship a basic set of components yet, so those components you tried to add are located inside the demo workspace.

When will we start to split up these components into a standard library, @ubruhin?

**Comment by rnestler** [comment]
@szg0000 You could try to download the LibrePCB Base library with the library manager: 
![library_manager](https://cloud.githubusercontent.com/assets/1435346/22890927/0a939124-f20e-11e6-9d41-41bfb787d69c.png)
It should contain the basic elements.

**Comment by szg0000** [comment]
Thanks.
I already downloaded that library, but still not works. My library manager version different also.
I "git cloned" it from the master branch. Are you working from the master branch?
![librepcb_library_manager](https://cloud.githubusercontent.com/assets/18247040/22891264/0ff82a48-f20f-11e6-9b7d-432970f3446a.png)

**Comment by ubruhin** [comment]
The libraries from the library manager are all empty because the file format is not yet considered as stable. My plan is to move components from the demo workspace into the "official" libraries as soon as the file format is stable. This will be the case after the library editor is in a usable state, which will take at least some months. Until then, the demo workspace is required to use LibrePCB.

**Comment by szg0000** [comment]
Is there any discussion or forum topic or meeting, where I can send ideas for the file format development? For schematic and for the board?

**Comment by ubruhin** [comment]
No, there is no special forum or similar for such discussions, so it's easiest to just open a new issue here to discuss about the file format. Maybe I'll create a separate repository for RFCs (like [rust-lang/rfcs](https://github.com/rust-lang/rfcs)) some time...

**Comment by szg0000** [comment]
A new issue here is enough for comments.

**Comment by ubruhin** [comment]
As this problem is clarified, I'll close this issue. Feel free to open a new issue to discuss about the file format.

**Comment by szg0000** [comment]
I still can't add component. Is the file format clarified?

**Comment by rnestler** [comment]
> No, there is no special forum or similar for such discussions, so it's easiest to just open a new issue here to discuss about the file format. Maybe I'll create a separate repository for RFCs (like rust-lang/rfcs) some time...

Actually we have the Telegram group which we sometimes use for discussions: https://t.me/LibrePCB_dev.

**Comment by ubruhin** [comment]
> I still can't add component. Is the file format clarified?

No, this is still work in progress. As long as I can't live with the money earned with LibrePCB, I need to go to work the whole week and thus the progress on LibrePCB is quite slow, so you need to be patient :wink:
