### ISSUE TITLE
ChaosPost from CCC Camp 2023

### ISSUE THREAD

**Issue by wowwood** [LibrePCB/LibrePCB#1483]
Postcard from CCC (Chaos Communications Camp) 2023 - https://events.ccc.de/camp/2023/infos/index.html

![2024-12-28 18 23 25](https://github.com/user-attachments/assets/a44f8da2-d68c-4ec6-b017-3868a97512ab)

![2024-12-28 18 23 16](https://github.com/user-attachments/assets/7bf958d6-fe07-4375-b34b-b67443d6cc68)

Apologies for the delay in delivery.

**Comment by ubruhin** [comment]
Haha thanks, but somebody else was faster by a year :joy: #1281

Maybe the postcard needs to be marked as delivered? :think

**Comment by rnestler** [comment]
I could pick it up

**Comment by rnestler** [comment]
I did pick it up :smile:

**Comment by ubruhin** [comment]
Nice :smiley:

**Comment by wowwood** [comment]
My apologies - it was on the "undelivered" pile so put it here :)
