### ISSUE TITLE
delete LibrePCB project

### ISSUE THREAD

**Issue by szg0000** [LibrePCB/LibrePCB#169]
Need to delete the LibrePCB project, because based on object oriented programming. The theory of object oriented programming failed due to the multiple inheritance problem. The object oriented programming is unnecessary and has logical errors.

We need a new project, based on non-object oriented programming.

**Comment by ubruhin** [comment]
WTF?!

> The theory of object oriented programming failed due to the multiple inheritance problem.

LibrePCB does not use multiple inheritance, except to implement multiple interfaces (base classes without data).

> We need a new project, based on non-object oriented programming.

Feel free to do that. LibrePCB will continue using OOP.
