### ISSUE TITLE
Create a "About LibrePCB" dialog

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#17]
The current about dialog is very simple and could be improved in many ways:
- [x] Replace the `QMessageBox` with an own class derived from `QDialog`. This new class should be called `AboutDialog` and created in the directory [`libs/librepcb/common/dialogs/`](https://github.com/LibrePCB/LibrePCB/tree/master/libs/librepcb/common/dialogs)
- [x] Add the new about dialog to the "Help" menu of all main windows (ControlPanel, SchematicEditor, BoardEditor)
- [ ] Add more information to the new dialog, maybe splitted up in multiple tabs:
  - [x] A small description about LibrePCB (inclusive Logo)
  - [x] A link to LibrePCB's website (librepcb.org) and to the GitHub project site
  - [x] The application's version / commit hash (determined by `git describe`)
  - [x] Maybe the datetime of the last commit
  - [x] The license (a link to http://www.gnu.org/licenses/gpl-3.0.html, or the whole license text)
  - [x] Options for contribution (Bitcoin address, link to Patreon)
  - [x] Maybe a "how to contribute" section (see also #12)
  - [ ] Maybe the rendered content of the [AUTHORS.md](https://github.com/LibrePCB/LibrePCB/blob/master/AUTHORS.md) file

**Comment by dbrgn** [comment]
Since PR #213 was closed, I plan to give this another attempt with classical UI 🙂

**Comment by ubruhin** [comment]
Fixed in #261
