### ISSUE TITLE
Improve reusability of graphics items

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#181]
The code for drawing some graphics items like footprints or symbols exist multiple times because of slightly different requirements.

For example a resistor shown in the library editor looks like this:
![auswahl_011](https://user-images.githubusercontent.com/5374821/29945123-3c468ec2-8ea0-11e7-9809-83ceeb80cfe6.png)

And when adding the same symbol (as part of a component) to a schematic, it looks different:
![auswahl_012](https://user-images.githubusercontent.com/5374821/29945140-4f8fad42-8ea0-11e7-8f0d-83e6cdd7692e.png)

To avoid code duplication it would make sense to make these graphics items more generic, so they can be used in different situations.

**Comment by dbrgn** [comment]
Good idea. But observe the [rule of three](https://erikbern.com/2017/08/29/the-software-engineering-rule-of-3.html) :slightly_smiling_face:

**Comment by ubruhin** [comment]
Just found a bug which could be solved when refactoring the graphics items: The rendered text height in the library editor is not exactly the same as in the project editor.

> But observe the rule of three

Should be observed :smile: For example the code to render a symbol exists three times:
- [librepcb::library::SymbolGraphicsItem](https://github.com/LibrePCB/LibrePCB/blob/master/libs/librepcb/library/sym/symbolgraphicsitem.cpp)
- [librepcb::library::SymbolPreviewGraphicsItem](https://github.com/LibrePCB/LibrePCB/blob/master/libs/librepcb/library/sym/symbolpreviewgraphicsitem.cpp)
- [librepcb::project::SGI_Symbol](https://github.com/LibrePCB/LibrePCB/blob/master/libs/librepcb/project/schematics/graphicsitems/sgi_symbol.cpp)

**Comment by dbrgn** [comment]
:ok_hand:
