### ISSUE TITLE
Support for Multi-PCB Projects

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#182]
Is there support for having multi-PCB projects?

I'm working on a project (in KiCad currently) where I want to split up the components of a schematic into three separate PCBs that will be connected with wires. Having all three PCBs in the same Gerber export with V-cuts in between would be perfect.

KiCad can't do it. If LibrePCB does not support it yet either, then this is my official feature request :slightly_smiling_face:

**Comment by ubruhin** [comment]
No, LibrePCB does not have a multi-PCB feature. I have added this feature request to our [wishlist](https://github.com/LibrePCB/LibrePCB/wiki/Wishlist) and will now close this issue.

Multi-PCB projects may be useful for multiple things:
- Creating mixed PCB panels (for Gerber export)
- Creating BOM for all PCBs of a project
- Rendering 3D models of stacked PCBs

Btw, creating mixed PCB panels is often done by a standalone software, see [this StackExchange answer](https://electronics.stackexchange.com/questions/158335/how-to-panelize-gerber-files) for some examples.
