### ISSUE TITLE
LibrePCB needs a sexy gui. Something like Saleae Logic

### ISSUE THREAD

**Issue by 0xB767B** [LibrePCB/LibrePCB#19]
![Uploading SaleaeLogic.png…]()

**Comment by ubruhin** [comment]
@0xB767B where is the picture? :)

**Comment by rnestler** [comment]
Is this still relevant? I would vote to close it to not clutter the issue list.

**Comment by dbrgn** [comment]
For the record, this is what Saleae Logic looks like:

![download](https://cloud.githubusercontent.com/assets/105168/16668997/95685c18-4493-11e6-8c88-6f557d935748.jpg)
![saleae_logic_1](https://cloud.githubusercontent.com/assets/105168/16668998/95823624-4493-11e6-898e-ef082bdcc8b8.png)

I don't think we should strive for that look at all :)

**Comment by rnestler** [comment]
Closed because not applicable. (And because @0xB767B was also just trolling a bit :wink:)
