### ISSUE TITLE
Add support for copper planes in boards

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#196]
Copper planes are actually quite important, but not yet implemented in LibrePCB. Probably the most complicated part of planes is to calculate all segments of the plane, while every segment must satisfy various requirements:

- Keep clearance to other nets or objects (according to design rules)
- Ensure a minimum width at any point in the plane (remove plane segments which are too thin)
- Optionally connect pads by thermal relief
- Optionally remove segments which are not connected to any net (orphans)

I think this can basically be done with following steps:
1. Take plane outline polygon:
![auswahl_012](https://user-images.githubusercontent.com/5374821/33150848-b95b0804-cfd5-11e7-9513-aae0d1a04c41.png)
2. Take the outline of every object which must not be connected to the plane, and grow these outlines by their required clearance width:
![auswahl_015](https://user-images.githubusercontent.com/5374821/33150854-c01ac210-cfd5-11e7-982c-e10d4e387242.png)
3. Subtract these objects from the outline:
![auswahl_016](https://user-images.githubusercontent.com/5374821/33150862-c99c2e0a-cfd5-11e7-8248-1a4fdfba7f63.png)
4. Shrink (offsetting) the resulting segments by the minimum width value:
![auswahl_017](https://user-images.githubusercontent.com/5374821/33150892-e1af7eb6-cfd5-11e7-829f-c45185ba7a18.png)
5. Expand (offsetting) the resulting segments by the minimum width value:
![auswahl_018](https://user-images.githubusercontent.com/5374821/33150900-e93b9336-cfd5-11e7-987e-705a29cb7b90.png)
6. Fill the resulting segments:
![auswahl_019](https://user-images.githubusercontent.com/5374821/33150910-f6ba4c64-cfd5-11e7-8489-220c244b3a87.png)
7. Result (No thermal pads, keep orphans):
![auswahl_020](https://user-images.githubusercontent.com/5374821/33150920-00599f7c-cfd6-11e7-8625-081b04153d8b.png)

I used the [clipper library](http://angusj.com/delphi/clipper.php) for these operations, seems to work pretty good. The only disadvantage is that it doesn't support arcs in polygons, only straight lines are allowed. So we need to convert arcs to many small segments of straight lines :( Unfortunately I didn't find a library which can handle arcs...

Btw, I found some interesting papers about polygon offsetting:
- https://seant23.files.wordpress.com/2010/11/anoffsetalgorithm.pdf
- http://www.me.berkeley.edu/~mcmains/pubs/DAC05OffsetPolygon.pdf

**Comment by dbrgn** [comment]
Awesome! 🎆

**Comment by sebgonzo** [comment]
Great work!
Don't worry not supporting arcs right now. I'm sure that Altium is also using lines instead.
I think that you should think about unconnected copper islands removal function or at least option to manually place polygon cutouts.

**Comment by dbrgn** [comment]
Yeah, cutouts / keepout areas are important, but probably pretty simple to implement once we have the copper plane feature.

**Comment by nimish** [comment]
CGAL can handle circular arcs, and there are fast and accurate algorithms for approximating bezier curves with circular arcs and lines, if you need that.

**Comment by nimish** [comment]
Hmm, I took a look through this problem. CGAL discussed adding support for polygons with circular arcs here http://cgal-discuss.949826.n4.nabble.com/Inset-and-offset-of-General-polygon-set-2-with-circle-arcs-td4661729.html for the offset operation. Unfortunately, it seems to be dead.

**Comment by ubruhin** [comment]
Yes, it seems to be really hard to find a library which can perform polygon offsetting with support for circular arcs :( For the moment I will just use the Clipper library, we could still switch to another library some time if there is one which supports circular arcs...

> I think that you should think about unconnected copper islands removal function

I'm working on that :)

**Comment by ubruhin** [comment]
> I suspect you could use an approximation algorithm like Tiller and Hanson?

No, LibrePCB doesn't use beziers but only circular arcs which are pretty easy to approximate by linear line segments ;)

**Comment by kliment** [comment]
Looking through the kicad and horizon codebase they also segment arcs.
