### ISSUE TITLE
Can not delete any board!

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#198]
after add a board by accident and try to delete it i found nowhere to delete the board 
if i deleted the file , i will never open up the project 
here's the image
![new board](https://user-images.githubusercontent.com/6311930/33241373-4d96eade-d2ff-11e7-9eb0-49aca127b039.png)
![not exist](https://user-images.githubusercontent.com/6311930/33241374-4dccec60-d2ff-11e7-9585-92a901dc0783.png)

**Comment by ubruhin** [comment]
This is not yet implemented. When deleting the board file manually, you also need to remove the board from the file core/boards.lp. Then you should be able to open the project again.

**Comment by ubruhin** [comment]
Fixed in 7fc2cb861fabc5965c5cb31c0dcda484b0fd2ac0 -> removing boards is now possible.
