### ISSUE TITLE
Use libxml2 instead of Qt DOM

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#2]
Low level tasks:
- [ ] Include the [libxml2](http://xmlsoft.org/) library as a [pkgconfig](https://www.freedesktop.org/wiki/Software/pkg-config/) package to project files.
- [ ] Add the new `libxml2` dependency to the [README.md](https://github.com/LibrePCB/LibrePCB/blob/master/README.md), [.travis.yml](https://github.com/LibrePCB/LibrePCB/blob/master/.travis.yml) and [appveyor.yml](https://github.com/LibrePCB/LibrePCB/blob/master/appveyor.yml).
- [ ] Use `libxml` in [XmlDomDocument](https://github.com/LibrePCB/LibrePCB/blob/master/libs/librepcbcommon/fileio/xmldomdocument.cpp) and [XmlDomElement](https://github.com/LibrePCB/LibrePCB/blob/master/libs/librepcbcommon/fileio/xmldomelement.cpp). 

High level tasks:
- [ ] Save XML files in canonical form (required for version control) _[high priority]_
- [ ] Validate XML files with XSD _[low priority, can be done in a later release]_

Please have a look at the branch [use_libxml2](https://github.com/LibrePCB/LibrePCB/tree/use_libxml2) to see what's already done.

**Comment by ubruhin** [comment]
@rnestler Interested to work on this issue? Canonical XML has very high priority because without this, version control of LibrePCB's XML files is a pain...

**Comment by rnestler** [comment]
Seems like a isolated enough task so that I won't break to much :wink:

**Comment by dbrgn** [comment]
Does libxml protect against XML attacks?

You should probably take a look at https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#C.2FC.2B.2B.

**Comment by rnestler** [comment]
@dbrgn The link you provided suggests, that it protects against those attacks, doesn't it?

**Comment by dbrgn** [comment]
If you set the right options, then probably, yes.

**Comment by dbrgn** [comment]
Here's a list of attacks on XML: https://pypi.python.org/pypi/defusedxml#attack-vectors

**Comment by ubruhin** [comment]
This should no longer be required because the root problem is solved by #162, so I'll close this issue.

**Comment by rnestler** [comment]
Is it still desired to use libxml2 in the future?

**Comment by ubruhin** [comment]
> Is it still desired to use libxml2 in the future?

Not sure, depends on how good the actual solution works and how libxml2 still can improve LibrePCB.
