### ISSUE TITLE
Use a more Pull-Request oriented developement process

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/LibrePCB#20]
@ubruhin You currently push a lot directly to master. To be more in touch with the development it would be nice if you could open pull-requests per feature/bug-fix. This would give other developers the chance to review the changes, make suggestions and also track the progress of librepcb.
Adding a `@foo please review` note in the pull-request also encourages others to review the pull-request.

**Comment by ubruhin** [comment]
Good advice, I'll try to follow it!

**Comment by rnestler** [comment]
So we consider this closed?

**Comment by ubruhin** [comment]
:+1:
