### ISSUE TITLE
Library editor menu items are counter-intuitive

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#200]
![can not remove anything](https://user-images.githubusercontent.com/6311930/33375807-187b9cde-d546-11e7-9f26-cb84e29088f5.png)
hope you can fix

btw: if you choose another two to have a try , you wlll see all three was blue and cannot delete any of them

**Comment by ubruhin** [comment]
Oh that's a misleading GUI. These menu items should be disabled if no library element is open. To remove whole library elements, currently the only way is to open it and then choose File -> Remove Element.

**Comment by 243750496** [comment]
find still no able to delete anythins with File -> Remove Element. and update library
 **maybe it's a bug**
![no use of delete elements](https://user-images.githubusercontent.com/6311930/33400796-21c7b11e-d592-11e7-9361-0cb1beffb89f.png)

**Comment by 243750496** [comment]
![right way to do delete element](https://user-images.githubusercontent.com/6311930/33420695-82b372d0-d5ea-11e7-9a42-960a9f80403f.png)
this is the rightway to do delete , in main page after opened the library manager , we can not delete it 

only can delete it with opened the item , please correct it ,  it's a worg guide to show up in main page without function

**Comment by ubruhin** [comment]
@0xB767B Maybe you could improve the GUI to avoid confusion? Most important would be to disable/enable some menu items depending on the current state of the library editor.

**Comment by 0xB767B** [comment]
@ubruhin Are there any general concepts in LibrePCB how to enable/disable menu-items based on some state of the program?

**Comment by ubruhin** [comment]
Not really. I guess the library editor is currently the only window which enables/disables some `QAction`s depending on which kind of library element is currently open. And the implementation of that is quite pragmatic ;)

Btw, now I noticed that some `QAction`s in the toolbars are disabled properly, but not their corresponding menu items (most `QAction` objects are added to both, a toolbar and a menu).

**Comment by lukabosnjakovic** [comment]
I had similar problem few minutes a go. It is not intuitive that you must first open element and than go to Edit > Remove. My proposal is that maybe you add context menu (right click on element) with remove option. This is more intuitive to me.

**Comment by dbrgn** [comment]
I'd nominate this for the 0.1 final :slightly_smiling_face:

**Comment by ubruhin** [comment]
I'm ready to accept pull requests ;)

**Comment by ubruhin** [comment]
Context menu added in #380.

> Btw, now I noticed that some QActions in the toolbars are disabled properly, but not their corresponding menu items (most QAction objects are added to both, a toolbar and a menu).

Fixed in c0d39eb020d2b6c839a18fb7a0af1f5764d13dfd.
