### ISSUE TITLE
after import library there's no component there

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#201]
Steps:
1.i create my own libraries but can not find anywhere to add components from my lib (not empty)
and 

2.then i tried to copy it to new working space and load it , but still can't add any components of mine (create by myself , not copy and not reedit ),

3.at last i try to recreate all and delete demo working space but with try several times of restart still get a empty list 

Q:could you please help me?

![no components](https://user-images.githubusercontent.com/6311930/33376101-4c1be700-d547-11e7-8e1e-8ac7062d7c8b.png)

# btw: i hope you can add import from outside lib folder function to get easy share the 3-party-lib with others

**Comment by 243750496** [comment]
sloved by create a component at second of creation 
first: create a symbol
then:create a component
final : we can see it in libraries

btw:if more useful please set keywords in it

**Comment by 243750496** [comment]
Q:what is required? what's the different between check the mark or not check it?
![required](https://user-images.githubusercontent.com/6311930/33429209-cffe30e0-d606-11e7-942c-431b654ebfd0.png)

**Comment by 243750496** [comment]
get puzzled much more:
![puzzle 1](https://user-images.githubusercontent.com/6311930/33430461-8eb8c19a-d60b-11e7-9148-e8bbbb33ee15.png)

![puzzle 2](https://user-images.githubusercontent.com/6311930/33430511-b63ea0d6-d60b-11e7-8a73-5116b4aa5491.png)

NQ1: why symbol pin can't edit to change it's name?
NQ2: what's the two list in image means 
NQ3: what can they do for me if i choose one for each of them?just an sign for nothing or done something witch is very important of designing?

**Comment by 243750496** [comment]
![2 more question](https://user-images.githubusercontent.com/6311930/33431139-30e0a0ee-d60e-11e7-9714-c842c65d185f.png)

2More Question 1 :what is Footprint Variants means ?why it can add more ? will it be conflicated with previous one?if not what will happpend if i set two of them?

2:why we need set pad name ?

**Comment by ubruhin** [comment]
I'm sorry, I can't explain every detail here and now. But basically you can just use the default values, they are fine for most cases. If you still have questions, please ask us in [our IRC channel](https://webchat.freenode.net/?channels=#librepcb).

Basically we need to create documentation for end users to clarify all of your questions. I created #205 to work on that.

I guess this issue could be closed now (?).

**Comment by 243750496** [comment]
i hope you can add import from outside lib folder function to get easy share the 3-party-lib with others
not just copy the library to the working space 
i mean maybe we can pack it up and use it to import  instead
