### ISSUE TITLE
why aligement up move downwards ?while center is not center

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#202]
![center1](https://user-images.githubusercontent.com/6311930/33422008-1008fb92-d5ef-11e7-884e-95f8d3d6045b.png)

![center2](https://user-images.githubusercontent.com/6311930/33422014-15992104-d5ef-11e7-9a57-e983a4a8cb73.png)
after setting axis the position is correct now 
![right aligenment](https://user-images.githubusercontent.com/6311930/33422031-1c56c906-d5ef-11e7-8e89-764056cd8629.png)
but how strange it is that set right move left??

**Comment by 243750496** [comment]
New Q:do that means choos right equal to :
Position :right middle side of "#Name"
compare with :center of the map
then do alignment: align the right middle side of "#Name" to the center of the ground

am i right

**Comment by ubruhin** [comment]
> am i right?

Yes. The alignment defines where the origin (the thin cross) of the text is located.

@243750496 Please use [our IRC channel](https://webchat.freenode.net/?channels=#librepcb) for questions - We use GitHub issues for bug tracking, not for providing support.
