### ISSUE TITLE
LibraryEditor: Tab title is not updated when changing component or device name

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#203]
![no use with hit enter](https://user-images.githubusercontent.com/6311930/33433787-f21dee3e-d617-11e7-9aec-71b5c7a69919.png)
**i mean hit enter to finish editing (_and remove the cursor focusing_) , this function should be add**

**and update the name of tabs automaticly without save and chose then reopen to get the change
 or will be puzzled what's the real name is it(Axoplas or Axoplast)**
![no able to save](https://user-images.githubusercontent.com/6311930/33434090-240796ce-d619-11e7-92a2-7b2a48ddf7a9.png)

## btw: i found same function but go in opposite way in pacage creating , it update the name of tabs in time no need reopening the component
![like pacage](https://user-images.githubusercontent.com/6311930/33434831-75edc830-d61b-11e7-9831-79dd0e1e2611.png)

**Comment by ubruhin** [comment]
The instant update did not work for components and devices. Fixed in cb3f9f576295ff2f80459ff659fe6ea99538a66c.

Thanks for reporting :)
