### ISSUE TITLE
Library editor error: "The category ... does not exist in the library database"

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#204]
![not exist in lib database](https://user-images.githubusercontent.com/6311930/33434566-a1e2516e-d61a-11e7-888a-182754949af4.png)

what happend ?do it can be able to use without cause problem?how to fix it?

**Comment by ubruhin** [comment]
This is a bug in the library editor which is quite easy to fix :) Someone interested in creating a pull request?

Hint: Look at the console output to see where the error occurs, set a breakpoint there and go up the callstack :wink:

**Comment by rnestler** [comment]
@ubruhin Did you assign me to mentor the issue or to fix it?

**Comment by dbrgn** [comment]
FIXIT FIXIT FIXIT!!!11!11eleven

**Comment by ubruhin** [comment]
Of course to fix it. I though this issue perfectly suits your skills :rofl:
