### ISSUE TITLE
can not save with logic error

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#206]
![logic error](https://user-images.githubusercontent.com/6311930/33467138-47ab4502-d68d-11e7-8030-6d1462ed83a8.png)

more info: i just added some pins then it show up the yellow bar , then i choose save , then i got the error and can not save the  modification 
### even with chose the tab and choose save before exit!!!!!!

**Comment by ubruhin** [comment]
Even if the error message is different, this is a duplicate of #208. Probably you have placed pads which are not assigned to any of the pads in the Pads list. To define a strategy how to handle such cases is part of #157.
