### ISSUE TITLE
Not possible to grab graphics items under a polygon

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#207]
![can not choose the hole](https://user-images.githubusercontent.com/6311930/33468167-43ec823e-d695-11e7-9d74-27c4e675ab0b.png)
first add the rectangle then draw the hole inside
though i set no grab 
it still can not allow me to choose the hole to edit its preference

btw：i this the best way to slove it (if now is not a good design) is to allow us to set layers 
then choosing will be easily ( like kicad)

![like kicad](https://user-images.githubusercontent.com/6311930/33468255-f9ec8e8a-d695-11e7-83b5-b2d7a0fa10a2.png)

**Comment by ubruhin** [comment]
Should be fixed (or at least improved) with 28fa4fbdd4fce9336afa78a6211e045a26aadb1f.
