### ISSUE TITLE
the library elements can not be saved because is not valid 

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#208]
![element not valid](https://user-images.githubusercontent.com/6311930/33470598-1c807a98-d6a4-11e7-877c-7fb2af002113.png)
how to reproduce the bug:
1:create a symbol and draw the elements 
2.creat the component and save
3.reedit the symbol
4. update the library
5.save

### so i hope if it's a bug plese get this way fix it :
**get a dynamic link to link the component and the symbol(_once one is update the other will also get update automatically_ ) then it will be easy to use**

BTW: i also hope to get a shortcut (ctrl+A) to replace the mouse choosing to choose all the elements while drawing

**Comment by 243750496** [comment]
maybe 2 GND lead to the problem???
![maybe gnd cause the problem](https://user-images.githubusercontent.com/6311930/33471027-4079e090-d6a6-11e7-9e95-375181340778.png)
**how to fix it?**

**Comment by 243750496** [comment]
plese add link function , here is a test 
![add the link function 1](https://user-images.githubusercontent.com/6311930/33471233-51cb6fca-d6a7-11e7-97d8-d1ddf7358ca7.png)
![add the link function 2 tx0](https://user-images.githubusercontent.com/6311930/33471241-5897e022-d6a7-11e7-85e0-3c6f64a5db6e.png)

**Comment by 243750496** [comment]
is it useful to difference the GND Mark???????? 
i think it's also ok to allow us to set normal mark not with number to difference it

![no need to difference gnd](https://user-images.githubusercontent.com/6311930/33471351-e6e699cc-d6a7-11e7-88d3-fbcc180bda21.png)
no i have able to save now

**Comment by ubruhin** [comment]
This is a problem of how invalid objects are handled, which is discussed in #157.
