### ISSUE TITLE
Please add 2 function: copy elements & copy text

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#209]
i can not paste(**while type ctrl+v nothing happened**) and copy elements to get a quick start of project
if each time i will do the samething it will be waste of time and boring
i hope you can fix it 
thx a lot
![add copy fuction and copy text to fill function](https://user-images.githubusercontent.com/6311930/33472075-7a8f6e44-d6ab-11e7-85a8-fe2ec12a7478.png)

**Comment by 243750496** [comment]
![cant paste](https://user-images.githubusercontent.com/6311930/33477157-97d3c3d8-d6bf-11e7-97ef-9d0c1e57215e.png)
1.if i want to make a matrix without copy and paste like now , it would be a vary difficult working ,
2.and if i can't add a text or show up the change the name  or value (it will not show up like i said now ) , i will easily get puzzled and difficult to compare with what i designed (missing some key or not)

**Comment by 243750496** [comment]
btw: i add changed the Text to Axoplast and the name to #NAME 
like this
![change](https://user-images.githubusercontent.com/6311930/33477821-157acd3e-d6c2-11e7-80c8-dd0b3279d5ac.png)

but still nothing happend i think it's your fault that you do not create a dynamic link to the Symbol 
please fix it
![still same](https://user-images.githubusercontent.com/6311930/33477797-fe29e3cc-d6c1-11e7-902b-6fe3ee09c827.png)

**Comment by 243750496** [comment]
if i delete the component then recreated the component in database updated but you will see a **bug :**
that database changed while using it there's no change
![bug with no update](https://user-images.githubusercontent.com/6311930/33478075-09fc68c2-d6c3-11e7-809a-e38a3322332e.png)

**Comment by 243750496** [comment]
though i changed the name to #Name of the Symbol name it still show up an old one with no change(both component and already added components ) 
![bug with name function](https://user-images.githubusercontent.com/6311930/33478434-3ab9a5e6-d6c4-11e7-8212-fbdee98dfe37.png)

**Comment by 243750496** [comment]
BTW: is it also a bug that the one should be 1 used the 2 instead?(in image there have two 2 , as you can see), maybe it's a bug signal?
![why 1 changed to 2](https://user-images.githubusercontent.com/6311930/33479175-1e0d3d7e-d6c7-11e7-8569-dac3dc17ecda.png)

**Comment by 243750496** [comment]
all i have now:
![all i have](https://user-images.githubusercontent.com/6311930/33486744-2c46a208-d6e6-11e7-9b3b-3ee00633bd97.png)

**Comment by ubruhin** [comment]
@243750496 Thank you very much for testing LibrePCB and reporting bugs. But unfortunately you do that in a very impolite way. Statements like "**still have bug !!!!!!!!!!!!!!!!!!!!!!!!!!!!**", "**please fix it**" or "**it's a bug!**" make me really angry. In addition, you really mess up the issues, create comments on issues which do not have any relation and so on. We cannot work that way, we need very much time to tidy up everything. We're not a company, we don't have a support department, we don't get paid for that work (except some donations).

I also already wrote you two times that this is not a support forum, but you still use it like that. Please use our IRC channel for support questions. I'm really sorry but I decided to prevent you from creating new issues/comments. You can still contact us in our IRC chat.

Thanks.

**Comment by dbrgn** [comment]
@243750496 you can find our chat here: https://webchat.freenode.net/?channels=#librepcb (or with any IRC client connected to #librepcb on freenode). it's the better place to ask for support than on github.

a lot of things simply aren't quite finished yet. if you want to use librepcb at this stage you'll need some patience and/or willingness to contribute code fixes :) we hope to be able to publish a first preview release in the next few months.
