### ISSUE TITLE
Library editor: First sort tables numerically, then alphanumerically

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#210]
![plese change the sort of the list](https://user-images.githubusercontent.com/6311930/33473429-612d41b4-d6b1-11e7-85fc-75f1110957ec.png)

it's so easy to make mistake to set 1-9 with insert 10-12
plese fix it, thx much more

right with the correction
![correct](https://user-images.githubusercontent.com/6311930/33473537-ca878e4e-d6b1-11e7-9cba-aaf8dc59b13c.png)

**Comment by dbrgn** [comment]
I'll try to fix it if I find out how to do it within ~20 minutes :P
