### ISSUE TITLE
CII Best Practices Badge

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#219]
Might be good to add the CII best practices badge to the README :)

https://bestpractices.coreinfrastructure.org/

It's quite some work to fill all the forms, but it can be done step by step.

**Comment by ubruhin** [comment]
Never heard about that before, but looks interesting, maybe I'll give it a try :)

**Comment by dbrgn** [comment]
It's mostly oriented towards infrastructure software (e.g. OpenSSL, Nginx, etc), so not all things are applicable. But I think there are a lot of good recommendations in there :)

**Comment by ubruhin** [comment]
Moved to https://github.com/LibrePCB/librepcb-rfcs/issues/3
