### ISSUE TITLE
Eagle Import: Error message: "There is no element of type "pad" with the UUID ... in the list."

### ISSUE THREAD

**Issue by hephaisto** [LibrePCB/LibrePCB#223]
I tried importing some random library from Autodesk to check the import system (I used the lib for OZ9938, for the sake of completeness).
When I try to "Add" the device in the board editor, I get the error message "There is no element of type "pad" with the UUID ... in the list."
Looking at the package.lp, I see that there are two distinct sets of UUIDs in the file, one for the package `(pad .. (name "1"))` (I will reference this as A from here on) and one for the footprint `(pad ... (side top) (shape rect)` (referenced as B).
The error goes away when assigning a name to the footprint pad, which also changes B to match A.
When I add another footprint with named pads, the resulting file gets a third pad instance which also has the same UUID as A.

To resolve, I ask the following question: Should footprint pads (B) have their own UUID (=>1) or are the UUID fields in the file just a reference to the node defined in A (=>2)?
Variation 1 would mean that there are some serious issues with the way references are handled and needs some rework around the file structure.
Variation 2 can maybe be solved by omitting UUID management for footprint_pads in the eagle importer, because they don't have their own UUID anyway.

I can work on this issue in the second case, but I guess I'd need a bit of mentoring to get that done.

**Comment by ubruhin** [comment]
That's funny, I also noticed this bug just a few days ago :grin: 

Then I quickly fixed the bug and pushed to the `develop` branch (to get CI feedback), but afterwards forgot to merge it into master. So I did it right now: f743296d34277376f855b8f8e10fb84ac28411a5

In the commit you can see that your second assumption is true, the Eagle Importer shouldn't create separate UUIDs for footprint pads but use the package pad UUIDs instead.

> I can work on this issue in the second case, but I guess I'd need a bit of mentoring to get that done.

Oh that would have been very nice, unfortunately I fixed it already :crying_cat_face: But there are some more open issues, any help is welcome :smiley:
