### ISSUE TITLE
LogicError when connecting two vias

### ISSUE THREAD

**Issue by hephaisto** [LibrePCB/LibrePCB#226]
When I try to connect two vias (of the same signal), it produces a LogicError in
`LibrePCB/libs/librepcb/project/boards/items/bi_netpoint.cpp` on line 295:
```
 else if (isAttachedToVia()) {
        // check if netsignal is correct (would be a bug if not)
        if (&mVia->getNetSegment() != &mNetSegment) {
            throw LogicError(__FILE__, __LINE__);
        }
        mVia->registerNetPoint(*this); // can throw
    }
```

**Comment by ubruhin** [comment]
Yep, this is a known bug because the board editor is still very provisional. Beside this bug, there are also several other bugs in the board editor...

Until the board editor is refactored, I add a note to the documentation: https://github.com/LibrePCB/librepcb-doc/pull/1

**Comment by ubruhin** [comment]
Oh I forgot to write that there is a workaround for this bug: Instead of connecting a trace to the via, start a new trace from the via and connect it to the end of the existing trace. (via-->trace instead of trace-->via).
