### ISSUE TITLE
Multiple PCB views

### ISSUE THREAD

**Issue by UweBonnes** [LibrePCB/LibrePCB#229]
Hello,

when a late design change requires a new route to be laid out from one edge of a complex board to the opposite edge, two simultanious views of the board would be useful:
- one magnified view of the areas where you actual route
- another global view showing where you are in the context of the whole board.

**Comment by dbrgn** [comment]
We just discussed that yesterday 🙂 I added it to the [wishlist](https://github.com/LibrePCB/LibrePCB/wiki/Wishlist).

**Comment by UweBonnes** [comment]
Somebody asked me on FOSDEM to enter my wish.

**Comment by dbrgn** [comment]
Yes, that was probably @ubruhin. We will reopen this issue once it becomes feasible to implement it, for now the priority is to get a first release out though.
