### ISSUE TITLE
Change minimum required Qt version back to 5.2.x

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#23]
In many Linux distributions, Qt 5.4 is not yet available via package manager. To support more distributions (like Ubuntu >= 14.04), it would be better to support Qt 5.2.x. This should be possible with only a few small code changes (+ updating the documentation / Travis CI config).

**Comment by rnestler** [comment]
@Luz Maybe you care about this?

**Comment by Luz** [comment]
mkay
