### ISSUE TITLE
Provide nightly builds for macOS

### ISSUE THREAD

**Issue by Geekly** [LibrePCB/LibrePCB#250]
Can macOS installation instructions be added to the Getting Started guide? macOS is included in the compatibility in several places, so it seems appropriate to have either explicit installation instructions or a disclaimer that it's not yet available (coming soon).

[https://docs.librepcb.org/getting_started/#gettingstarted-installation](https://docs.librepcb.org/getting_started/#gettingstarted-installation)

**Comment by ubruhin** [comment]
Hi @Geekly,
Actually LibrePCB *does* run on macOS, but we have no experience with mac (and also don't have such hardware), so we're not able to provide any executables for mac. We would need somebody who integrates that into our CI system, then we could also provide nightly builds for mac. Maybe you are familiar with development of mac applications? :)

If you compile LibrePCB as described in [README.md](https://github.com/LibrePCB/LibrePCB/blob/master/README.md#development), you can already use LibrePCB on mac.

Anyway, I agree that it makes sense to add this information to the getting started guide...

**Comment by Geekly** [comment]
Oh, I see! I'll give it a try then. I do wish I were experienced enough to help out with providing nightly builds. I'll see if I can get it built myself first.

**Comment by Geekly** [comment]
I'm working on compiling now, and I wanted to track a few extra steps that I needed to take for the first time installation under macOS and Docker via the instructions below:

[https://github.com/LibrePCB/LibrePCB/tree/master/dev/docker](https://github.com/LibrePCB/LibrePCB/tree/master/dev/docker)

I got to `./build_container.sh` without issue. When I ran that, a lot of things built until I got the following error:

`xauth: command not found` 
That led me to install xquartz on my system. Apparantly XWindows systems doesn't come on mac by default anymore. This might need to be mentioned in the Docker instructions. At that point I believed I needed to install xquartz on my system, outside of the Docker environment.

I did `brew install caskroom/cask/xquartz` and installed xquartz.

It installed, and now the error has changed. I started the docker container using `./run_container.sh` and tried to launch librepcb got the `QXcbConnection: Could not connect to display :0` error. This was predicted in the help file, but the recommended fix did not work.

I've tried the command `xhost +local:docker` and now get the `xhost:  unable to open display ""` error. That's where I am now.

So, my system was missing prequisites for XWindows and there's still some issues withe my system. But, I think the compile went okay, I just can't launch it.

**Comment by ubruhin** [comment]
> I'll give it a try then.

Great!

But to be honest, I'm not sure if using Docker on mac is the way to go. Doesn't Docker on mac runs Linux containers (instead of mac containers)? If so, I think a librepcb executable built in a Docker container can't run on mac machines outside of Docker. Then we can't deploy these executables as nightly builds for mac.

Generally I would suggest to build LibrePCB directly on a mac os host (instructions are in the README.md). Then the built executable and the files from the "share" directory need to be packaged as an application bundle. Such bundles could then be deployed as nightly builds.

Maybe these links help you creating bundles: 
- https://doc.qt.io/qt-5/osx.html#deploying-applications-on-macos
- https://doc.qt.io/qt-5/osx-deployment.html

If you are successful, the required commands can be added to our [CI configuration](https://github.com/LibrePCB/LibrePCB/blob/master/.travis.yml).

**Comment by Geekly** [comment]
That could very well be the case about Docker and macOS. From the installation instructions here, it implied that Docker was a solution for any installation. I'm moving on the to mac specific instructions to see how that goes.

**Comment by Geekly** [comment]
Following the mac-specific instructions worked flawlessly. It might be helpful to others if it were suggested that Docker not be used for the mac, since it could be mistakenly interpreted that Docker is a solution for all platforms. At least, that's what happened in my case.

**Comment by ubruhin** [comment]
I opened an issue in the docs repository for the documentation part of this issue: https://github.com/LibrePCB/librepcb-doc/issues/10

> It might be helpful to others if it were suggested that Docker not be used for the mac, since it could be mistakenly interpreted that Docker is a solution for all platforms.

Yeah this could be improved. Feel free to open a pull request to fix it :)

**Comment by ubruhin** [comment]
In #265 I started to deploy *.dmg files for Mac, it is now available as a nightly build here:
https://download.librepcb.org/nightly_builds/master/librepcb-nightly-mac-x86_64.dmg

@Geekly Could you maybe try if that *.dmg file works? As I don't have a Mac, I can't try it...

**Comment by ubruhin** [comment]
Now we have (untested) nightly builds for Mac (see also https://github.com/LibrePCB/librepcb-doc/pull/11), so I'll close this one. Just let me know if they don't work...
