### ISSUE TITLE
Set up community translation project

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#270]
We should have a simple way for the community to contribute and fix translations.

Transifex is a great tool for this, and free for open source: https://www.transifex.com/

TODO:

- [x] Set up Transifex for a test run
- [ ] Document how to contribute translations

**Comment by ubruhin** [comment]
Yep, good idea :+1: 

I created a project here: https://www.transifex.com/librepcb/librepcb-application/.

**Comment by dbrgn** [comment]
Nice!

We should also create a translation guide. One part of that is "how to translate", the other one should be how to consistently translate technical terms.

We should for example create a table for all languages where we can specify how to translate words like "component" or "device". Otherwise we'll end up with inconsistent and confusing translations.

**Comment by ubruhin** [comment]
@dbrgn I guess translation works pretty good so far, so can we close this issue?

**Comment by dbrgn** [comment]
Yes!
