### ISSUE TITLE
Improve error messages for invalid library elements

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#288]
##### LibrePCB VERSION

Commit d7d9096ec

##### OS / ENVIRONMENT

Arch Linux

##### SUMMARY

Please tell me what I did wrong :slightly_smiling_face: 

![screenshot](https://tmp.dbrgn.ch/screenshots/20180717141433-abi_d1jl.png)

**Comment by dbrgn** [comment]
It seems that the reason in this case was duplicate pin names.

1. Why is this disallowed? The pins have a UUID for disambiguation.
2. There should be feedback already when creating the invalid pin. We could colorize all duplicate pin names with red.
3. In the error message, there should be a hint on what the user did wrong.

**Comment by dbrgn** [comment]
> if they are electrically connected, one GND pin in schematics is enough

That's one of the points where I was very unsure on how to model the symbol. It would be really useful if that could be shown somewhere. Similar to the package wizard, where you show this useful hint:

![img](https://tmp.dbrgn.ch/screenshots/20180717190851-owd0u89e.png)

**Comment by ubruhin** [comment]
> It would be really useful if that could be shown somewhere. Similar to the package wizard, where you show this useful hint:

I did not yet integrate it into the symbol editor (in contrast to the package wizard, the symbol wizard has no page to add pins), but at least I added a note to the getting started guide: https://docs.librepcb.org/#gettingstarted-libraries-sym

In addition, with #296 it will be possible to save a symbol even if it has multiple pins with the same name. Later we can show at least a warning in that situation...
