### ISSUE TITLE
Library Editor: Unreadable text on component signals list

### ISSUE THREAD

**Issue by SaculRennorb** [LibrePCB/LibrePCB#304]
##### LibrePCB VERSION
 0.1.0 (first_pcb-655-g6b08041-dirty)

##### OS / ENVIRONMENT
win7 x64

##### SUMMARY
when creating a new component via the dialog the leftmost text in the component signals table is unreadable because the font-size is too large / the row height is too small

##### STEPS TO REPRODUCE
create a new component via the new component dialog in the library editor

##### EXPECTED RESULTS
being able to read the text

##### ACTUAL RESULTS
cant read the text

![image](https://user-images.githubusercontent.com/18741506/44610052-be3afe80-a7fa-11e8-9825-30eef4127906.png)

**Comment by SaculRennorb** [comment]
same problem in the 'overview tab' once the component is finished, see [Image](http://prntscr.com/kki3u7)

**Comment by ubruhin** [comment]
Hmm maybe that only occurs on Windows, at least on Linux Mint I can't reproduce it...
