### ISSUE TITLE
Schematic Editor: Circle grab area of symbols not working

### ISSUE THREAD

**Issue by SaculRennorb** [LibrePCB/LibrePCB#311]
##### LibrePCB VERSION
0.1.0 (first_pcb-655-g6b08041-dirty)

##### OS / ENVIRONMENT
win7x64

##### SUMMARY
circle grab area isn't working on (custom) components , rectangle grab area works tho

##### STEPS TO REPRODUCE
create a custom component that uses a circle in its symbol and set the checkbox for grab area, then put it into your schema  - you will only be able to move the symbol by draging it on its center point, not the whole circle
##### EXPECTED RESULTS
circle with the checkbox set should define a grab area 

##### ACTUAL RESULTS
circles don't have a grab area

**Comment by ubruhin** [comment]
Should be easy to fix in https://github.com/LibrePCB/LibrePCB/blob/master/libs/librepcb/project/schematics/graphicsitems/sgi_symbol.cpp.
