### ISSUE TITLE
Install icon to PREFIX/share/icons

### ISSUE THREAD

**Issue by Alexander-Wilms** [LibrePCB/LibrePCB#313]
##### LibrePCB VERSION

81e7eb8

##### OS / ENVIRONMENT

Fedora 28
##### SUMMARY

`PREFIX/share/icons/hicolor/scalable/apps/librepcb.svg` and `PREFIX/share/icons/hicolor/scalable/mimetypes/` are the preferred location to install the icons, which also makes packaging easier.
[Freedesktop icon spec](https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html)
##### STEPS TO REPRODUCE

1. Build and install LibrePCB
##### EXPECTED RESULTS

Icon should be installed to `PREFIX/share/icons/hicolor/scalable/apps/librepcb.svg`
##### ACTUAL RESULTS

Icon is installed to `PREFIX/share/pixmaps/librepcb.svg`

**Comment by ubruhin** [comment]
Thanks for pointing this out @Alexander-Wilms, sounds like a simple and reasonable change.

PR welcome :)

**Comment by Alexander-Wilms** [comment]
I've created some similar patches for projects using cmake or autotools, so I'll try. However, the only place mentioning pixmaps is https://github.com/LibrePCB/LibrePCB/blob/68577ecf8f39299ef4d81ff964b01c3908d1f10b/dist/installer/packages/librepcb.nightly.app/meta/installscript.qs . Is that the right place to look?

**Comment by ubruhin** [comment]
> I've created some similar patches for projects using cmake or autotools, so I'll try.

Great :smiley: 

> Is that the right place to look?

Basically the "share" directory is copied 1:1 to `PREFIX/`, so there is no *.pro file or something like that to adjust. Only the file `installscript.qs` depends on the images path, so yes, that's the only file to adjust.
