### ISSUE TITLE
User created symbols don't show up in the 'Add Component Dialog' of the schematic editor.

### ISSUE THREAD

**Issue by sparkylein** [LibrePCB/LibrePCB#332]
##### LibrePCB VERSION
Version: 0.1.0 (first_pcb-692-gfa0a67e-dirty)
Build date: 2018-09-09 12:14:38 (PDT)

##### OS / ENVIRONMENT
macOS HighSierra
Version 10.13.6 (17G65)

##### SUMMARY
User created symbols don't show up in the 'Add Component Dialog' of the schematic editor.

##### STEPS TO REPRODUCE
1. Library Editor: Create new Component Categories 
2. Library Editor: Create new Symbol in a newly created Component Category
3. Schematic Editor: Open 'Add Component Dialog'
4. Schematic Editor - Add Component Dialog: The new categories are listed 
5. Schematic Editor - Add Component Dialog: Select newly created component category
6. Schematic Editor - Add Component Dialog: Newly created Symbol is not listed 
 
##### EXPECTED RESULTS
Newly created symbols should show up in the 'Add Component Dialog' of the schematic editor.

##### ACTUAL RESULTS
Newly created symbols do not show up in the 'Add Component Dialog' of the schematic editor.

Even added a new category with new symbol in the LibrePCB Base library, but the symbols are not listed in the 'Add Component Dialog' either...

**Comment by ubruhin** [comment]
Hi,

The "Add Component Dialog" only shows *Components*, not *Symbols*. So you have to create a component in the library (see docs [here](https://docs.librepcb.org/#gettingstarted-libraries-cmp)) and assign it to a category. Then it should show up in the dialog.

**Comment by sparkylein** [comment]
Hello,
thank you for your answer.

What is weird for me is that a schematic frame (this is the symbol I created...) is not an electrical component.
Therefore I would have never expected to have to create a component...
After I did what you said (and was mentioned in the docs) it worked as expected.

Granted, didn't fully read the documentation before playing with this program  : P

IMHO a program is only intuitive if the user interface guides an experienced user 'automatically'.

BTW: If LibrePCB would be my app I'm developing, I would change the wording:
Symbol -> Entity
Component -> Symbol
But it could also be that I didn't fully grasp the idea behind your wording choices...

**Comment by ubruhin** [comment]
> What is weird for me is that a schematic frame (this is the symbol I created...) is not an electrical component.

Yeah, currently we handle every "thing" you can place on schematics the same way, no matter if it has electrical connections or not. Maybe we can add special handling for non-electrical things some day...

> IMHO a program is only intuitive if the user interface guides an experienced user 'automatically'.

I agree, but unfortunately it's often not easy to implement it in such an intuitive way ;) But of course there are many things in LibrePCB which can be made more intuitive.

> BTW: If LibrePCB would be my app I'm developing, I would change the wording:
Symbol -> Entity
Component -> Symbol
But it could also be that I didn't fully grasp the idea behind your wording choices...

I guess you didn't fully grasp the idea :grin: Maybe this documentation helps to understand the concept: https://developers.librepcb.org/df/d4f/doc_library.html

I'll close this issue as the actual issue is solved.

**Comment by rnestler** [comment]
@sparkylein We could discuss the general library concept in the https://github.com/LibrePCB/librepcb-rfcs repository which is aimed at more broad and general discussions.

**Comment by ubruhin** [comment]
With fce256203ef0cfc7b2f99bb83cb3997d71ae6d3e, a warning is now shown in the component editor if the component is not added to a category - I think now users should immediately see what they have to do :)

**Comment by sparkylein** [comment]
Thank you for putting time into this.
(even though the issue is closed...)
:)
