### ISSUE TITLE
Any critical changes needed before the first release?

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#339]
I guess the current state of the project is ready for the first release :smiley: 

Does someone think there are still things which need to be done before the first release?
- Very critical bugs?
- Missing extremely important features?
- Critical file format issues?
- Critical concept issues?
- Something else?

But keep in mind: the first release (candidate) doesn't need to be perfect ;) Small bugs are not that bad, as long as they are not too annoying for the user. And of course features like a DRC would be nice, but that can be added in a later release...

And now: TEST, TEST, TEST, REVIEW, REVIEW, REVIEW! :smile:

**Comment by dbrgn** [comment]
What about the PNS router? Is there a lot of work left to include that?

**Comment by ubruhin** [comment]
That's not really critical ;)

And I'm still waiting until someone creates a standalone library for the PNS router (see https://github.com/LibrePCB/librepcb-rfcs/issues/1#issuecomment-413439122)...

**Comment by ubruhin** [comment]
No critical issues reported -> start creating the release :)
