### ISSUE TITLE
Schematic Editor: Allow placing symbol with double click

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#344]
##### SUMMARY

When listing symbols, allow placing a certain symbol by double clicking it. Right now, the user has to click "OK".

![screenshot](https://i.imgur.com/NOKLvm0.png)

In the screenshot above, double clicking "LED" in the middle column should place the LED symbol.

**Comment by robbawebba** [comment]
@dbrgn I would like to give this a shot! This would be the first Qt-based project I'll work on, so I would like to run my thoughts by you to be sure I've got the correct approach.

Currently the "OK" and "Cancel" buttons fulfill the `accept()` and `reject()` slots of the containing `AddComponentDialog`. When double-clicking an item in the tree view, the item generates an `itemDoubleClicked` signal. So we'll want to handle that signal and have it mimic the behavior of the "OK" button? So this signal will also fill the `accept()` slot of `AddComponentDialog`?

**Comment by ubruhin** [comment]
> @dbrgn I would like to give this a shot! This would be the first Qt-based project I'll work on, so I would like to run my thoughts by you to be sure I've got the correct approach.

Great! :smiley: 

> Currently the "OK" and "Cancel" buttons fulfill the accept() and reject() slots of the containing AddComponentDialog. When double-clicking an item in the tree view, the item generates an itemDoubleClicked signal. So we'll want to handle that signal and have it mimic the behavior of the "OK" button? So this signal will also fill the accept() slot of AddComponentDialog?

Yes, sounds good so far :)
