### ISSUE TITLE
Allow to export schematics as picture

### ISSUE THREAD

**Issue by madpipeline** [LibrePCB/LibrePCB#345]
##### SUMMARY
Currently the only means of exporting schematics are via PDF, which is very useful, but it would also be very beneficial to be able to export it as an image.

##### SOLUTION
Ideally to be able to export in both PNG and SVG, so that we have both a graphical format and a vectorial format.

**Comment by ubruhin** [comment]
Yes, that would be great, and probably not too hard to implement. I only wonder if such a feature should export only a single schematic, or all schematics at once (with an incrementing number in the filename or so)? The PDF export of course exports all schematics at once.
