### ISSUE TITLE
Readme: Add build instructions for windows

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#35]
- how to install Qt libraries and MinGW
- how to set up the build configuration while opening librepcb.pro the first time with Qt Creator

@nemofisch This is an issue for you :)

**Comment by rnestler** [comment]
This is more like build instructions isn't it?

**Comment by ubruhin** [comment]
> This is more like build instructions isn't it?

Jo, fixed ;)

**Comment by ubruhin** [comment]
I guess this should now be clear enough in the readme...
