### ISSUE TITLE
Allow to choose or create a workspace when one is already opened

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#352]
##### SUMMARY
Currently the "first run wizard" is the only way to create a new workspace interactively (asking for location and initial settings). After opening an existing workspace, it's no longer possible to create a new workspace interactively. The only way is to choose "File" -> "Switch Workspace" in the control panel and choose an empty directory, but that's not intuitive and doesn't allow to set the initial workspace settings.

##### IMPLEMENTATION

I think it would be nice if the "Switch Workspace" menu item just shows the "first run wizard", but without its first page ("Welcome to LibrePCB"). That way the user could interactively choose an existing or create a new workspace. Maybe the `FirstRunWizardDialog` should be renamed to `WorkspaceChooserDialog` or so, and the visibility of the welcome page should be configurable.

**Comment by rummanwaqar** [comment]
I can take this issue

**Comment by ubruhin** [comment]
@rummanwaqar cool, looking forward for a pull request! :smiley: Don't hesitate to ask if you have any questions :)
