### ISSUE TITLE
Library Editor not saving upon exit

### ISSUE THREAD

**Issue by ouabache** [LibrePCB/LibrePCB#356]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.0-rc1
Git Revision:     d49c0a70e23f5690e4d5785684ef828e04c2cb26
Build Date:       2018-10-21T12:05:18
Qt Version:       5.9.1 (built against 5.9.1)
CPU Architecture: x86_64
Operating System: Ubuntu 18.04.1 LTS
Platform Plugin:  xc
```

##### SUMMARY
Changes made when editing components

##### STEPS TO REPRODUCE
On both a local and remote lib I tried to rotate the symbol on a component. Each time it worked but it failed to save the result

##### EXPECTED RESULTS
symbol should have changed in the lib

##### ACTUAL RESULTS
lib was not changed

**Comment by ubruhin** [comment]
Thanks for reporting :) Fixed in 84359b78fbf1a0eab587fd7728f3cd1ea306678b.
