### ISSUE TITLE
macOS: white text on white background + pixelated symbols

### ISSUE THREAD

**Issue by hitsfromdabong** [LibrePCB/LibrePCB#382]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.0-unstable
Git Revision: 3e7d3cccff
Qt Version: 5.11.1
Operating System: MacOS Mojave
...
```

##### SUMMARY

There's white text on white background all over the place. See the three screenshots I've appended. Also some of the symbols look pixelated on a retina display.

PS: Already checked whether macOS' dark mode was the problem. Unfortunately it's not.

![shot1](https://user-images.githubusercontent.com/42746238/48991320-c9bbff80-f132-11e8-9016-e92572461056.png)
![shot2](https://user-images.githubusercontent.com/42746238/48991322-caed2c80-f132-11e8-899b-82ef1f3e3e49.png)
![shot3](https://user-images.githubusercontent.com/42746238/48991323-cc1e5980-f132-11e8-85c3-9096e73d5b8a.png)

**Comment by ubruhin** [comment]
Hmm strange. Could you check if this also happen with the official stable release from https://librepcb.org/download/?

**Comment by hitsfromdabong** [comment]
I've just checked. It doesn't happen with the stable release, but there is no support for dark / light mode, only a neat light interface.

**Comment by ubruhin** [comment]
OK, interesting... Unfortunately I can't help here as I don't have a Mac ;)

**Comment by dbrgn** [comment]
There doesn't seem to be an issue when using the 0.1.0 stable DMG release on a MacBook Air with High Sierra:

![screen shot 2018-11-29 at 09 25 53](https://user-images.githubusercontent.com/105168/49208864-4102c500-f3b9-11e8-8f1f-9486f720ed49.png)

![screen shot 2018-11-29 at 09 26 51](https://user-images.githubusercontent.com/105168/49208867-45c77900-f3b9-11e8-990c-d80e7e23206b.png)

(Some dialogs have some problems though, see the cut-off text...)

![screen shot 2018-11-29 at 09 26 35](https://user-images.githubusercontent.com/105168/49208888-54ae2b80-f3b9-11e8-9058-f12e577c6c1c.png)

**Comment by hitsfromdabong** [comment]
Just pulled the newest source and recompiled using qt 5.12.0. Looks proper now. I suspect the bug to have been in the qt release. 

Please close.

**Comment by alfishe** [comment]
Found at least one progress control background inconsistency on MacOS Mojave
![image](https://user-images.githubusercontent.com/245354/58374082-9bfb1c00-7f05-11e9-90e3-91c1c102fd50.png)

**Comment by ubruhin** [comment]
Closing this issue because it was reported a long time ago with a much older LibrePCb version. During my own tests, I never experienced this issue. If it still exists, feel free to reopen.
