### ISSUE TITLE
Library Editor: Allow to change position of Symbol Pin "Name" label

### ISSUE THREAD

**Issue by Symbian9** [LibrePCB/LibrePCB#383]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.0
Git Revision:     d7458d3b3e126499902e1a66a0ef889f516a7c97
Build Date:       2018-11-24T16:25:35
Qt Version:       5.9.1 (built against 5.9.1)
CPU Architecture: x86_64
Operating System: Debian GNU/Linux 9 (stretch)
Platform Plugin:  xcb
```

##### SUMMARY

"Name" label of pins added in bad position and there are no any way how change it.

##### STEPS TO REPRODUCE

1. Create new local library;
2. Add new symbol;
3. Start editing of this symbol;
4. "Add Symbol Pin".

##### EXPECTED RESULTS

Each symbol pin should has option to set "Name" label position (or remove "Name" label) via "Pin Properties" dialog.

##### ACTUAL RESULTS

After adding each symbol pin has own "Name" label that could not be moved or removed.

##### ADDITIONAL INFORMATION

![pic.1](http://i.imgur.com/gjFXheQ.png)

![pic.2](http://i.imgur.com/TLZcyl0.png)

**Comment by ubruhin** [comment]
Moving the pin name is not possible yet, but I agree that sometimes it would be useful.

If you want to hide the pin name, you need to do it in the component editor, see https://github.com/LibrePCB/librepcb-rfcs/issues/31.
