### ISSUE TITLE
Checking LibrePCB with PVS-Studio Inside a Docker Container

### ISSUE THREAD

**Issue by AndreyKarpov** [LibrePCB/LibrePCB#394]
Small article about checking LibrePCB with static code analysis tool: https://www.viva64.com/en/b/0598/

**Comment by dbrgn** [comment]
Thanks for doing this analysis! I leave the evaluation of the results to @ubruhin :slightly_smiling_face: 

LibrePCB is vendoring in some libraries as git submodules: https://github.com/LibrePCB/LibrePCB/tree/master/libs It seems that at least some of the results are coming from library code (e.g. hoedown or delaunay-triangulation). If that's the case, have you considered reporting the issues to the upstream projects too?

You mention something about a free-for-open-source license policy. Is that a perpetual license? Is it licensed in a way that would allow all contributors to access the tool, and that would let us periodically run the analysis in CI?

**Comment by ubruhin** [comment]
Very nice, thanks @AndreyKarpov! :smiley: 

I fixed most of the issues you documented in your blog, see #395 (but only issues in our own code, not 3rd-party libraries).

Regarding "Dangerous use of dynamic_cast":

> The pointer returned by the dynamic_cast operator is passed to the function handleMouseWheelEvent and dereferenced in it without any prior check. This is unsafe because the dynamic_cast operator could return nullptr. It means this code is no better than the faster static_cast.

I suspect this warning is emitted mostly for casts from `QEvent*` to various subclasses of `QEvent`. At (hopefully) all places where we do this, we either checked the type of the event with [`QEvent::type()`](http://doc.qt.io/qt-5/qevent.html#type), or implicitly know what type the event has.

We could use `static_cast` in these cases, but often we check the pointer returned by `dynamic_cast` with `Q_ASSERT()`, so we can detect logic errors during development. With `static_cast` we can't perform these checks as it would always return a pointer != nullptr.

**Comment by AndreyKarpov** [comment]
> You mention something about a free-for-open-source license policy. Is that a perpetual license? Is it licensed in a way that would allow all contributors to access the tool, and that would let us periodically run the analysis in CI?

I want to apologize for the late answer. I had to wait for the article on Free PVS-Studio for those who develops open source projects to be published so I could share the link: "[Free PVS-Studio for those who develops open source projects](https://www.viva64.com/en/b/0600/)". Yes, you can use PVS-Studio in CI. You can learn more about CI in [documentation](https://www.viva64.com/en/m/#ID0ERLAC).

**Comment by ubruhin** [comment]
The reported issues were fixed in #395 and so far I don't intend to do anything else regarding this topic, so let's close this issue...
