### ISSUE TITLE
Device editor messages: Warn if no signals are connected

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#412]
When creating a new device, show a warning message if there are pads, but no pads have been connected to a component signal.

**Comment by bcallebaut** [comment]
Can you elaborate ?
I did the following:
- I created a dummy symbol with 5 pins
- I created a dummy a package with 5 pins
- I created a Device based on the created symbol and package.
There is no warning/message if I let the pins unconnected in the messages box.
Is that what you want to add ?

**Comment by dbrgn** [comment]
Hm, it's a while since I created this issue, but yes, I think that's what I meant:

![img](https://tmp.dbrgn.ch/screenshots/20190719102550-q_blz45j.png)

Two pins, not connected to any component signal.
