### ISSUE TITLE
Add support for slotted pad holes

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#418]
##### SUMMARY

Some THT footprints require pads with slotted holes, i.e. obrounds. So we should add support for them.

##### SOLUTION

Maybe just add a second dimension to the size information of the pad's drill, i.e. X/Y size instead of a diameter. In the Excellon output, use the G85 command if X and Y sizes aren't equal.

**Comment by dbrgn** [comment]
Example: This footprint with oval / obround pads:

![image](https://user-images.githubusercontent.com/105168/63650770-af10c880-c74e-11e9-9d94-5d412f0d2b6f.png)
