### ISSUE TITLE
Fix doxygen build warnings

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#43]
Since all classes were moved into a new namespace "librepcb" (1d361e6a33e4ff12ede683da00f7211ea93b100f), doxygen now throws lot of warnings like `warning: explicit link request to 'SomeClass' could not be resolved`

I would mentor this issue if someone wants to work on it.

**Comment by javsanpar** [comment]
I would like to work on this issue 😄. I'm going to build doxygen to see the warnings.

**Comment by ubruhin** [comment]
> I would like to work on this issue

Great! :+1: 

Just let me know if you have any questions :)

**Comment by ubruhin** [comment]
Fixed in #537.
