### ISSUE TITLE
Add text annotations to schematic

### ISSUE THREAD

**Issue by st599** [LibrePCB/LibrePCB#441]
##### SUMMARY

On some schematics it is useful to be able to have small notes added:

- Firmware files to be blown to IC
- Routing or placement requirements
- Reasons as to why certain components are added etc.

##### SOLUTION
Add a text box tool with basic formatting controls (size, colour, bold, bullet list) to allow users to place useful information on schematics to help other readers to understand the circuit, the reasoning etc.
This is separate from the net labeling tool, and is ignored by the placement algorithms.

**Comment by ubruhin** [comment]
Yes this is needed for sure. There is already a discussion how this could be implemented: https://librepcb.discourse.group/t/add-text-functionality-to-schematic-editor/19

I'll add this to the 0.2.0 milestone.
