### ISSUE TITLE
Compile error in "optional.hpp" with MinGW 4.8

### ISSUE THREAD

**Issue by cailei0596** [LibrePCB/LibrePCB#452]
some errors :

  TL_OPTIONAL_11_CONSTEXPR T &get() & { return this->m_value; }
  TL_OPTIONAL_11_CONSTEXPR const T &get() const & { return this->m_value; }
  TL_OPTIONAL_11_CONSTEXPR T &&get() && { return std::move(this->m_value); }

E:\MyWork\pcb\librepcb-0.1.1\libs\optional\tl\optional.hpp:434: error: expected ';' at end of member declaration
   TL_OPTIONAL_11_CONSTEXPR T &get() & { return this->m_value; }
                                   ^
E:\MyWork\pcb\librepcb-0.1.1\libs\optional\tl\optional.hpp:434: error: expected unqualified-id before '{' token
   TL_OPTIONAL_11_CONSTEXPR T &get() & { return this->m_value; }
                                       ^
anyone has encountered this problem?

**Comment by ubruhin** [comment]
Hmm what compiler version do you have exactly? I just noticed that 4.8.1 seems to be the minimum required version to compile `tl::optional`. If you have >= 4.8.1, could you check if it compiles after replacing the file `libs/optional/tl/optional.hpp` with the version from [here](https://github.com/TartanLlama/optional/blob/master/tl/optional.hpp)?

**Comment by ubruhin** [comment]
Closing this because of missing activity and related to an outdated version of LibrePCB. Feel free to reopen if the problem still exists.
