### ISSUE TITLE
Build release 0.1.1 fails with gcc9

### ISSUE THREAD

**Issue by luigino** [LibrePCB/LibrePCB#460]
Using openSUSE Tumbleweed and gcc 9 I see [this](https://github.com/LibrePCB/LibrePCB/files/3244878/librepcb_gcc9.txt).

It build properly on openSUSE Leap 15.x with either gcc7 or gcc8.

**Comment by ubruhin** [comment]
Seems to be caused by the `debug_assert` library, see https://github.com/foonathan/debug_assert/issues/17 for details (and workaround).

Once they have fixed it, we need to update to the latest revision of the library, so I'll keep this issue open.

**Comment by Petross404** [comment]
Hmm it seems gentoo has a [problem](https://bugs.gentoo.org/686228) as well...
