### ISSUE TITLE
CI: Use Ubuntu 16.04 or 18.04 for the Doxygen build job

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/LibrePCB#461]
##### SUMMARY

Currently the Doxygen build step runs on an Ubuntu 14.04 Docker image. Ubuntu 14.04 is end of life since April 2019, so it makes sense to move to Ubuntu 16.04 or 18.04. See also https://github.com/LibrePCB/LibrePCB/pull/458

##### SOLUTION

Fix the issues with Doxygen on newer Ubuntu version and change the build job.

**Comment by ubruhin** [comment]
Fixed in #635.
