### ISSUE TITLE
The GitHub Sponsor botton shows an error

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/LibrePCB#463]
##### SUMMARY
Clicking the GitHub Sponsor button shows an error:
![librepcb-sponsors](https://user-images.githubusercontent.com/1435346/59093701-d789e300-8914-11e9-8e84-1d6884d4ebde.png)

##### STEPS TO REPRODUCE
Click the GitHub Sponsor button.

##### EXPECTED RESULTS
Showing how to sponsor the LibrePCB developers

##### ACTUAL RESULTS
The error message

##### ADDITIONAL INFORMATION
I think @ubruhin needs to join the Sponsors waitlist for the error to disapear: https://github.com/sponsors
![github-sponsors](https://user-images.githubusercontent.com/1435346/59093886-3b141080-8915-11e9-9267-5572a5064b5a.png)

**Comment by ubruhin** [comment]
> I think @ubruhin needs to join the Sponsors waitlist for the error to disapear

I did it already some time ago, but I can do nothing else than waiting to get accepted ;)

**Comment by ubruhin** [comment]
Fixed :)
