### ISSUE TITLE
Connection "required/optional" checkbox

### ISSUE THREAD

**Issue by mwit-a** [LibrePCB/LibrePCB#475]
##### SUMMARY
In my opinion, the 'connection required' column can be improved. 
I think it is not intuitive if you need to check a checkbox with the label 'optional' to change the status to 'required'.

##### SOLUTION

Rename the column into 'Connection required' and just leave the checkboxes.

![required](https://user-images.githubusercontent.com/51746948/60593955-24da6280-9da4-11e9-97c4-7c9d29daacef.png)

**Comment by ubruhin** [comment]
To be honest, the main reason why I did it that way is that in #456 I switched to the native checkbox support of `QTableView` which unfortunately does not allow to center the checkbox inside its cell, and the left aligned checkbox IMHO looks ugly. So I just added the text "Optional" resp. "Required" to the cell to make it looking better :grin: Actually I expected that this should even be more intuitive than a checkbox without text...

**Comment by rnestler** [comment]
> Actually I expected that this should even be more intuitive than a checkbox without text...

If one sees
 * [ ] Optional

one may assume that it is not Optional since optional is not checked.

**Comment by dbrgn** [comment]
I agree with that, it's a bit confusing :slightly_smiling_face:

**Comment by dbrgn** [comment]
Two potential solutions:

- A: Remove the checkbox label, but change the column label from "Connection" to "Required"
- B: Change the checkbox label to a static "Required" text

@ubruhin would you be happy with one of those two?

**Comment by ubruhin** [comment]
> @ubruhin would you be happy with one of those two?

- A: Would be fine for me if the checkbox is then centered, but I'm pretty sure it would be cumbersome to implement ;)
- B: Not as good as A, but probably still better than the current solution - so yes, would be fine for me :)
