### ISSUE TITLE
Allow to move vertices of copper plane

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/LibrePCB#482]
##### SUMMARY
Currently when drawing copper planes, one has to get it perfectly right the first time, since it is impossible to move vertices / edges after the polygon has been finished.

##### SOLUTION

Allow to select and move vertices.

**Comment by dbrgn** [comment]
Workaround: Double-click on the polygon edge. Then adjust the X/Y values.

![img](https://tmp.dbrgn.ch/screenshots/20190714014701-gcc0naxr.png)

**Comment by ubruhin** [comment]
Implemented in #774.
