### ISSUE TITLE
Improve Polygon Editor

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#483]
##### SUMMARY

The polygon editor is currently very limited. The biggest problem ist that rows can't be moved.

For example, here:

![img](https://tmp.dbrgn.ch/screenshots/20190713234909-lmoluimk.png)

...it's not easily possible to add more points between row 1 and 2.

##### SOLUTION

- Allow moving rows around
- Allow inserting rows below a selected other row
- Maybe allow copying rows

**Comment by EdizonTN** [comment]
Notice!
I try nightbuild and I found small problem:
Entering value into pos.X/Y of polygon segment in polygon properties window, is limited only 2 decimal places! Please, check it.



LibrePCB Version: 0.1.3-unstable
Git Revision:     466ea012804a28243fea50d877329a1c89cff945
Build Date:       2019-09-02T19:47:06
Qt Version:       5.11.3 (built against 5.11.3)
CPU Architecture: x86_64
Operating System: Windows 7 SP 1 (6.1)
Platform Plugin:  windows

**Comment by ubruhin** [comment]
Thanks for the report @EdizonTN, I opened #512 to track this issue.
