### ISSUE TITLE
Use Ctrl + W to close a Project

### ISSUE THREAD

**Issue by dns2utf8** [LibrePCB/LibrePCB#49]
Use Alt + F4 to close a Window

**Comment by rnestler** [comment]
I wouldn't expect Ctrl+W to close a Project, but to close a tab.

**Comment by dbrgn** [comment]
> Use Alt + F4 to close a Window

This should be handled by your window manager actually.

Is there a specification for this type of shortcuts? Maybe at freedesktop.org?
