### ISSUE TITLE
Feature Request: Workspace Settings: Custom Color settings

### ISSUE THREAD

**Issue by EdizonTN** [LibrePCB/LibrePCB#496]
##### SUMMARY
Custom color settings for each sections: library editor, sch. editor, pcb editor and their each graphics object (Pad, Via, Hole, Top Signal layer, Wire, Junction....). 

Each graphics object could be drawing by custom color. These colors presets, could be save to workspace settings file.

Why? Custom color system is better for designers. Each designer prefer own color scheme.
Again, Why? Try imagine, in your job (8 hour per day) you use commercial XY EDA system. You have fixed color for some object. And at home you want use LibrePCB for small DYI project. And you will lost in another color scheme...

##### SOLUTION
Custom setting can be accesible through workspace settings (for all sections separately: Library editor, sch. editor and pcb editor), and also in each section in separate menu Ex.: Edit->Preferences ->Colors.

Something like this: 
![screen2](https://user-images.githubusercontent.com/48570749/62757938-2cfd8000-ba7d-11e9-9b31-b21e2046e8a9.png)

After clicking to colored rectangle, will open color picker for selecting another color.
Like this:
![screen3](https://user-images.githubusercontent.com/48570749/62758063-8f568080-ba7d-11e9-80d8-656bc58ce819.png)

**Comment by ubruhin** [comment]
See also this related issue about background colors: #654
