### ISSUE TITLE
Schematic editor: Add move and rotate functionality, for Name and Value fields

### ISSUE THREAD

**Issue by EdizonTN** [LibrePCB/LibrePCB#515]
##### SUMMARY
In schematic editor will be beautiful, if component's fields "Name" and "Value" can be movable and rotateable.

##### SOLUTION
Example:
Default components place into schematic:
![edit_before](https://user-images.githubusercontent.com/48570749/64495203-2c802100-d297-11e9-9234-30d42bd9891e.png)

After Name and Value move and rotate:
![edit_after](https://user-images.githubusercontent.com/48570749/64495207-3d309700-d297-11e9-8c65-de511bad65c5.png)

**Comment by doom-fr** [comment]
Yes, it would be useful to save space ...

![image](https://user-images.githubusercontent.com/7809481/66714352-1560b180-edb6-11e9-858c-8642d8bebae7.png)

**Comment by EdizonTN** [comment]
Hello ubruhin,
Is it possible to increase priority of this feature request? Is able to implement in next version (0.1.6)?
Thanx.
