### ISSUE TITLE
Board editor: Allow rotate while moving device

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#528]
##### SUMMARY
In Board editor, you can move with drag and drop. You can also rotate by typing 'R'.
When you firstly place a device, you can move and rotate during the move without problem.
But when the device is already on the board, you can't rotate during a move.
You have to stop the move, make the rotation and restart the move to correctly place it.
It is painful.

##### SOLUTION
As it is already implemented (as it is possible in first placing), just activate the possibility to rotate during a move.
As we move and rotate devices many times during routing, it will be user friendly to do that.

**Comment by EdizonTN** [comment]
I agree. This will be more confortable.
But don't forget for user's key mapping: https://github.com/LibrePCB/LibrePCB/issues/495
