### ISSUE TITLE
Selection of stacked items

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#536]
##### SUMMARY
In Library Package editor (but maybe elsewhere), when there's different items stacked, you can only select the upper one.

![image](https://user-images.githubusercontent.com/7809481/66406549-19728500-e9ec-11e9-9475-91c03c6e11d0.png)

For example, here, I can't select the Documentation Layer rectangle of the pin as it is completely inside the pad on Top Layer.

I have to move the pad away, select the pin and do what I have to do and move the pad back.

##### SOLUTION
2 different solutions : 
1. when you select a point with stacked items, open a menu to choose the one you need
2. when you select a point with stacked items, firstly select the one that is inside others

Any of this solution will solve the problem.
And a mix of both will be perfect !

(layer filtering can also solve this problem but will not be user friendly in Board Editor)

**Comment by doom-fr** [comment]
great to be planned in 0.1.5 milestone. :+1:

**Comment by ubruhin** [comment]
With #748 this is fixed in the board editor, but other editors still have this issue.

**Comment by 5n8ke** [comment]
I'm currently working on implementing this for the schematic editor
