### ISSUE TITLE
Board editor: Add DRC (Design Rules Check)

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#539]
##### SUMMARY
In Board Editor, it seems that net clearance constraints are missing.
:fire::fire::fire: I succeeded in connecting VCC net to GND net ! :fire::fire::fire: 

##### SOLUTION
Implement net clearance, if possible in live.

(Think this is a main pcb software feature that is missing, and so it needs a high priority)

**Comment by dbrgn** [comment]
The board editor does not yet have an ERC (Electrical Rules Checker) implemented, that's still one of the big missing features. I'll rename the issue if that's OK for you. (If you meant something different, just leave a comment.)

**Comment by doom-fr** [comment]
OK for that renaming.
Just for me, Net clearance is the most important point of ERC.

Is there any workaround till the implementation ?

**Comment by dbrgn** [comment]
> Is there any workaround till the implementation?

No, unfortunately not :slightly_frowning_face:

**Comment by EdizonTN** [comment]
ERC - electrically rule check - apply in schematic
DRC - design rule check  - apply in PCB editor, includes also clearance/overlay/crossing two separate nets.

I recommend not swap these functions and naming.

**Comment by doom-fr** [comment]
https://en.wikipedia.org/wiki/Physical_verification

**Comment by dbrgn** [comment]
Good point, sorry :slightly_smiling_face: I always mix up those two.

**Comment by doom-fr** [comment]
Thanks to @ubruhin to set this as "High Prio".

I also found this link which can be useful (it is in python but might be easily be translated in C++) : https://stackoverflow.com/a/2824596/1619521

Maybe you have already something like that in LibrePCB as I have found that some clearance checks already exists in library editor : 

![image](https://user-images.githubusercontent.com/7809481/66639880-122fbf00-ec18-11e9-8274-d5409d962669.png)

![image](https://user-images.githubusercontent.com/7809481/66639910-283d7f80-ec18-11e9-9448-d8de3b6cc8fb.png)

Maybe this can be spread to DRC ?

**Comment by ubruhin** [comment]
I'll try to implement at least some of the most important checks - missing connections and short circuits. Afterwards we can add more checks step by step.

> Maybe you have already something like that in LibrePCB as I have found that some clearance checks already exists in library editor :

Yes, we already have such functions :)

**Comment by doom-fr** [comment]
I think that short circuit and clearance is quite the same : 
- short circuit : distance = 0 on different nets
    (for traces : distance between center segments < (width 1+ width 2))
- clearance : distance < clearance on different nets
    (for traces : distance between center segments < (width 1+ width 2 + clearance)
