### ISSUE TITLE
Package Editor: Create custom pad shape

### ISSUE THREAD

**Issue by EdizonTN** [LibrePCB/LibrePCB#540]
##### SUMMARY
Possibility of creating custom pad shapes

##### SOLUTION
My proposal:
Create a custom pad:
- Place into same copper layer, various object as: polygon, circle, line, hole or Pad. Or combination of these objects of course
- selecting these objects (click LMB + move over objects to select all)
- Click right mouse button - open popup menu - select "Create PAD" item (needs be added)
- now LibrePCB ask to user for selecting center point of this shape.
- After selecting pad center, is custom pad shape created and all objects are "grouped".
- double click on this new shape (custom pad), will open standard pad properties dialog with grayed checkboxes: Shape-Round, Rect and Octagon. Don't add a new shape checkbox "Custom". Can be problem with change from custom to others. Custom shape can be deleted or edit only.

Custom pad (group of objects) is now one object. Can be moved, rotated....

Modify a custom pad:
- RMB on existing custom pad - open popup menu - select "Break up Pad" item (needs be added). "Create Pad" is grayed now.
- and now apply same procedure as create pad.

LibrePCB now works with custom pad as with standard one - create solder mask with positive expansion and paste mask with negative expansion.

Requirements: 
- Minimal one object must be in copper layer (cannot create custom pad only by hole/s)
- If create custom pad with more than one objects, all object must be in same layer 
- Also, selected objects must be overlayed (electrically connected) - minimal is zero distance between objects margins. Otherwise objects will be ignored - even selected too.

Example (mystical):
Used object (Circle, polygon, line with arc filled, hole and std. pad):
![Objects](https://user-images.githubusercontent.com/48570749/66512494-5f594700-ead9-11e9-8f6b-42aef8b22c9e.png)

Created custom pad:
![custom_pad](https://user-images.githubusercontent.com/48570749/66512514-697b4580-ead9-11e9-878a-6944ead1122b.png)

**Comment by ouabache** [comment]
You could do this by simply making the footprint editor recursive. In other words you can select other footprints and group them together to create a new footprint.

You would create a set of footprints that are primitives to be used as building blocks that create other footprints. Each one could be rotated and given a unique instance name.

**Comment by ubruhin** [comment]
FYI, I implemented custom pad shapes now, but I decided to keep the concept pretty simple for now, see details in #1102. The UI could still be improved some day to make designing custom shapes easier (maybe with grouping objects together as suggested), but I think this should not affect the way how custom shapes are implemented under the hood.
