### ISSUE TITLE
librepcb 0.1.2 Schematic Editor loses Toolbar after second opening on Mac OS Mojave 10.14.6

### ISSUE THREAD

**Issue by shredda** [LibrePCB/LibrePCB#541]
##### VERSION / OS / ENVIRONMENT
LibrePCB Version: 0.1.2
Git Revision:     acdd94d9d2310f79215125b999153e9da88a9376
Build Date:       2019-07-13T21:11:21
Qt Version:       5.13.0 (built against 5.13.0)
CPU Architecture: x86_64
Operating System: macOS Mojave (10.14)
Platform Plugin:  cocoa

##### SUMMARY
When I open LibrePCB for the second time, the toolbox in the schematic editor is missing.
Instead, only the drawing canvas is visible.

##### STEPS TO REPRODUCE
1. Create new project
2. Open schematic editor
3. Restart LibrePCB
4. Open schematic editor: Toolbox is missing

##### EXPECTED RESULTS
I expected the Toolbox to come back like on the first time.

##### ACTUAL RESULTS
The toolbox is missing. Only the drawing canvas is there.

##### ADDITIONAL INFORMATION
In order to see the toolbox again, I have to remove the line
window_state from the section
[schematic_editor]
in ./.config/librepcb.org/LibrePCB.ini

<img width="1032" alt="Screenshot_schematic_with_tools" src="https://user-images.githubusercontent.com/38114669/66515315-2c19b680-eadf-11e9-861b-3fb4d1737f47.png">
<img width="1032" alt="Screenshot_schematic_without_tools" src="https://user-images.githubusercontent.com/38114669/66515316-2cb24d00-eadf-11e9-8b3d-fbf7405fb022.png">

**Comment by ubruhin** [comment]
This was fixed in #503 and will be included in the upcoming release v0.1.3.

In the mean time, a workaround is to disable OpenGL in workspace settings and then you need to remove the application settings file (file path according [Qt docs](https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes)) once.
