### ISSUE TITLE
Schematic Editor : only first (or no) device is good when adding multiple times the same

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#547]
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 0.1.3-unstable
Git Revision:     2e747216114042648c9677d7c18301b793b80918
Build Date:       2019-10-10T18:14:18
Qt Version:       5.12.3 (built against 5.12.3)
CPU Architecture: x86_64
Operating System: Ubuntu 18.04.3 LTS
Platform Plugin:  xcb
```

##### SUMMARY
When adding multiple time the same device, only the first one is good int the "Place Devices" dock the other seems to be the default device of the component.
When clicking "Auto-Add-All", none are good.

##### STEPS TO REPRODUCE
1. Open the "Add component" window
2. select the 1608 resistor device
3. insert it multiple times in the schematic
![image](https://user-images.githubusercontent.com/7809481/66750540-039e0d80-ee8d-11e9-86d2-1e7a868c9f2a.png)

4. go to board and checks devices

![image](https://user-images.githubusercontent.com/7809481/66750587-216b7280-ee8d-11e9-922f-cb30fe6c5fad.png)
***********
![image](https://user-images.githubusercontent.com/7809481/66750601-29c3ad80-ee8d-11e9-8217-f16da34f89e8.png)
***********
![image](https://user-images.githubusercontent.com/7809481/66750616-321be880-ee8d-11e9-9f05-3a67c111eaa4.png)

5. add all devices
=> all are bad ones
![image](https://user-images.githubusercontent.com/7809481/66750856-df8efc00-ee8d-11e9-96b2-4af6d54eab18.png)

6. remove all devices from the board
=> it goes to step 4
7. now add the first one with "Add" button
=> a 1608 resistor is added
=> now all others have the good device in the "Place Devices" dock
![image](https://user-images.githubusercontent.com/7809481/66751007-41e7fc80-ee8e-11e9-95e3-febebb8caae9.png)

8. But if you add all of them, none is good
![image](https://user-images.githubusercontent.com/7809481/66751162-a7d48400-ee8e-11e9-81db-1550f27cc06c.png)

:angry:

##### EXPECTED RESULTS
All are 1608 resistors

##### ACTUAL RESULTS
Just the first one is 1608.
Others are through hole ones.

**Comment by dbrgn** [comment]
@ubruhin candidate for 0.1.3?

**Comment by ubruhin** [comment]
Indeed, that's not good ;)
