### ISSUE TITLE
Create a scope guard class

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#55]
It would be very useful to have a scope guard class which makes it possible to execute multiple methods, which can throw exceptions, atomically. If one method throws an exception, all previously executed methods must be reverted.

How such a scope guard may be used (...not sure if the lambdas are properly used...?):
```C++
void MyClass::doSomethingAtomically(int magicNumber) throw (Exception)
{
    ScopeGuardList sgl;
    sgl.execute([this](){doSomethingOrThrow();},
                [this](){revertSomethingOrThrow();});
    sgl.execute([this, &magicNumber](int n){makeMagicThingsOrThrow(n);},
                [this, &magicNumber](int n){revertMagicThingsOrThrow(n);});
    sgl.execute([this](){fooOrThrow();},
                [this](){barOrThrow();});
    sgl.commit();
}
```

Such a class should be created in the static library [librepcbcommon](https://github.com/LibrePCB/LibrePCB/tree/master/libs/librepcbcommon) (namespace "librepcb") because it would be useful for all other libraries.

@rnestler Interested in implementing such a class? :smiley:

**Comment by rnestler** [comment]
Definitely interested! Feel free to assign me to the issue :smiley:
