### ISSUE TITLE
Board editor: Text in small pads not readable

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#580]
##### SUMMARY

On too little pads, the net name is not shown.
But there's enough place to do so.

![image](https://user-images.githubusercontent.com/7809481/68966984-8e9d5b00-07df-11ea-9b46-c763bdcfc1ca.png)

##### SOLUTION

change the net marking layout on little pads

**Comment by doom-fr** [comment]
And sometimes net names are cut

![image](https://user-images.githubusercontent.com/7809481/68977410-75ed6f00-07f8-11ea-94d9-9462c35e12c2.png)

**Comment by EdizonTN** [comment]
Change font size depends on Pad size on screen (zoom in/out)?

**Comment by doom-fr** [comment]
Sometimes there's enough place to write the name without changing the font size.
So first, should modify the name outbound.
And if it is not sufficient, effectively, shrink it to fit inside.

**Comment by ubruhin** [comment]
I think this has been fixed with #1136 (font size gets reduced to always fit into the pad) so let's close this :muscle:
