### ISSUE TITLE
Schematic and Board Editor : set warning if device is different and add device update functionality

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#584]
##### SUMMARY

There seems to be two ways of working with schematic/board editors : 
1. setting devices in the schematic (and so packages) before starting the board
2. setting just components in schematic and set devices in Board Editor.

I you work with the first way (which is the one I use), you can get differences between the one set on the board and the one in the schematic.

##### SOLUTION
Add a warning if the board and schematic devices are different.

It will be also useful to provide a device update functionality. If you update a device, it will suppress it and put the new one at same position and angle.

**Comment by doom-fr** [comment]
I think that for this issue and that one https://github.com/LibrePCB/LibrePCB/issues/585, a new panel with a listing of placed devices should be added.

**Comment by ouabache** [comment]
Another way to handle this is to not store the device info in the schematic, only store the component.
If you select a device for the schematic then store the component in the schematic and the device in the board file. That way if you set the device in the board then you are simply changing it rather than having two copies.

**Comment by doom-fr** [comment]
Yes, but for example capacitors have different size regarding to capacity, voltage, technology, ...
It depends on things that you can see on the schematic, not on the board.
So setting this on board editor is not easy.

**Comment by doom-fr** [comment]
This is really a problem. LibrePCB retain bad component and not the updated one.
It also produces errors in the BOM.

I think this is a bug.

> Of course all of the existing boards are always in sync with the schematics

![image](https://user-images.githubusercontent.com/7809481/83860221-4a43bf00-a71f-11ea-97a7-130b37b74df0.png)


Can't we at least add a warnings in the schematic ERC or elsewhere ?

**Comment by doom-fr** [comment]
Is there a workaround to know which one is good and which one is bad, without manually verify everything (which is a lot of work and a source of errors).

**Comment by doom-fr** [comment]
Seems that in fact BOM is ok.
But BOM is not in sync with fabrication files which retain bad components.
