### ISSUE TITLE
Board Editor: First point of polygon is doubled at the beginning

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#590]
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 0.1.3-unstable
Git Revision:     ffa210ce0add8a1a7e7566a0cb7423dabe27716e
Build Date:       2019-11-19T20:31:54
Qt Version:       5.12.3 (built against 5.12.3)
CPU Architecture: x86_64
Operating System: Ubuntu 18.04.3 LTS
Platform Plugin:  xcb
```

##### SUMMARY
When drawing a polygon, the first point is doubled at the beginning
(in addition to the last point in closed shapes)

##### STEPS TO REPRODUCE
1. draw a triangle
2. edit it

##### EXPECTED RESULTS
should be 4 points in the polygon.

##### ACTUAL RESULTS
there's 5 points in the polygon.

##### ADDITIONAL INFORMATION
![image](https://user-images.githubusercontent.com/7809481/69286467-98fe9100-0bf3-11ea-8119-73204661b973.png)

**Comment by dbrgn** [comment]
Thanks for reporting, I already showed this to @ubruhin but then forgot to open an issue :smile:
