### ISSUE TITLE
Board Editor: Prevent to move name or value fields instead of the device

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#591]
##### SUMMARY
when moving device with the left click of the mouse, it happens that you move the name or value field which is not intended. Then, you have to place it back to it place before trying to move that device again.

##### SOLUTION
1. not use the whole text area to select, but reduce the hang point to only a square area (side=min(width,height)) around the anchor, taking in account the alignment.
2. add additional key (MAJ, CTRL, ALT, ...) to move these fields
3. implement option 1 of this issue https://github.com/LibrePCB/LibrePCB/issues/536

**Comment by ubruhin** [comment]
I'd say selecting objects is now working pretty well with recent LibrePCB versions so there's nothing to do anymore regarding this issue. Feel free to comment & reopen if there are other opinions.
