### ISSUE TITLE
Please add FreeBSD to the list of supported platforms on https://librepcb.org/

### ISSUE THREAD

**Issue by yurivict** [LibrePCB/LibrePCB#592]
The FreeBSD port is now available: https://www.freshports.org/cad/librepcb/

So could you please add FreeBSD to the website?

Thanks!
Yuri

**Comment by ubruhin** [comment]
Hi,

Thanks for providing the FreeBSD port! :smiley: 
I created https://github.com/LibrePCB/LibrePCB.github.io/pull/35 to add it to our download page.

Regards

**Comment by yurivict** [comment]
Thank you!

Best,
Yuri
