### ISSUE TITLE
Library editor: No copper area

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#598]
##### SUMMARY
Some devices need to have "no copper" area.
![image](https://user-images.githubusercontent.com/7809481/69586221-2706bd00-0fe2-11ea-96d7-6eda41e4232b.png)

![image](https://user-images.githubusercontent.com/7809481/69586239-37b73300-0fe2-11ea-856e-1113cce7ba4a.png)

The problem is that when you have a plane, it is not possible to specify this

##### SOLUTIONS
In Library Editor, add "Top no copper", "Bottom no copper" & "Inners no copper" layers
(detail all inner layers is not needed)

In Board Editor, add a "no copper plane" tool. It it something like the plane tool but in negative.
It can help to solve manually what is not possible with the Library Editor solution.

**Comment by doom-fr** [comment]
I have added some precision in the solution paragraph above.

**Comment by dbrgn** [comment]
I think those zones are often called "Keepout Zone", right? It should not only affect the planes, but also result in DRC warnings if traces are crossing that area.

**Comment by doom-fr** [comment]
This is OK for me.
I just do not use the term "Keepout" as it is not 100% clear.
As sometimes you are not authorized to put component but you can put traces.
And sometimes, you cannot put silkscreen.

"No copper" is clear. But it can be "Top copper keepout area".

But I am french so maybe it is a problem with my English ;-)

**Comment by doom-fr** [comment]
When you will do that, I think it will be the occasion to add a similar functionality.
The possibility to define an area where it is not possible to draw trace, but possible to have plane.
It can be use to be sure to have a perfect full plane in a dedicated area.

**Comment by doom-fr** [comment]
And also the opposite, define an area where there should be no plane (but where we can draw wire).
The aim is to not have plane too close to the pin of a TQFP48 (for example) on the inside side, but to allow connection of wire to that pin from the inside.
This is for managing things under the device.
(Do not know if it is really clear).
