### ISSUE TITLE
Newline character in net names is not rejected

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#603]
##### SUMMARY
I just see that my project has 2 different gnd.

The first one that is "gnd"
![image](https://user-images.githubusercontent.com/7809481/69764923-47658180-1172-11ea-8369-0003a9224f2a.png)

And the second one that is "gnd\n"
![image](https://user-images.githubusercontent.com/7809481/69764893-34eb4800-1172-11ea-9fdb-2b3a40e55974.png)

![image](https://user-images.githubusercontent.com/7809481/69764956-606e3280-1172-11ea-91b2-eb87cb89e8fd.png)

##### SOLUTION

Raise ERC if invisible characters are used in net names

**Comment by doom-fr** [comment]
Get this error just after having change "gnd\n" to "gnd".
At the first try to put a via.

![image](https://user-images.githubusercontent.com/7809481/69765416-10906b00-1174-11ea-8d9f-e3bd4a333532.png)

**Comment by ubruhin** [comment]
Whooops, that should actually not be possible! It seems that somehow linebreaks are not rejected, but all other invalid characters are rejected properly :(

I'll fix this. But with the Bugfix, LibrePCB will reject opening projects which already contain linebreaks in net names. So you would need to manually rename the net to something else (a unique net name which is not used already).

**Comment by doom-fr** [comment]
I have already removed the line break.

**Comment by rnestler** [comment]
> I'll fix this. But with the bugfix, LibrePCB will reject opening projects which already contain linebreaks in net names. So you would need to manually rename the net to something else (a unique net name which is not used already).

Would we need to provide migration paths for such things?

**Comment by doom-fr** [comment]
I think that the probabilty to encounter this problem is very low.

So just documenting in this issue, where and how to change the errored net names will be enough.

D.
