### ISSUE TITLE
Board editor: Change color of inner layer 2 (too close of inner layer 1 color)

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#608]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.3-unstable
Git Revision:     bd616e14d1366486cf53cad8b8c7e3e67119d960
Build Date:       2019-11-17T15:33:39
Qt Version:       5.12.3 (built against 5.12.3)
CPU Architecture: x86_64
Operating System: Ubuntu 18.04.3 LTS
Platform Plugin:  xcb
```

##### SUMMARY
inner layer 1 & 2 are quite same color

##### STEPS TO REPRODUCE
1. set to 2 inner layers
2. draw something in each layer

##### EXPECTED RESULTS
all copper layers (at least the 4 firsts) should have different colors that are easily distinguishable.

##### ACTUAL RESULTS
inner layer 1 & 2 are quite same color

![image](https://user-images.githubusercontent.com/7809481/69250084-4f8c5280-0baf-11ea-9028-e2a176788330.png)

##### ADDITIONAL INFORMATION
And when inner1 is selected, it is really quite the same as inner2

![image](https://user-images.githubusercontent.com/7809481/69250155-6cc12100-0baf-11ea-968d-84589041c734.png)

##### SOLUTION
exchange between inner layer 2 color and inner layer 4 color.
that will give this stack of color : 
![image](https://user-images.githubusercontent.com/7809481/69251187-561bc980-0bb1-11ea-9159-db2416d00665.png)

**Comment by doom-fr** [comment]
editing `boards/board/settings.user.lp` file allow to change all colors.

**Comment by ubruhin** [comment]
@dbrgn Since you are the master of colors, maybe that's an issue for you? :grin:
