### ISSUE TITLE
Components didn't follow the grid

### ISSUE THREAD

**Issue by petus** [LibrePCB/LibrePCB#610]
Hi,
at first, thanks for your job. The PCB CAD looks better and better.
Now, I installed v 0.1.3 and I made example board with capacitors and resistors and I find out that the resistor didn't follow the grid.

![librePCB_0 1 3](https://user-images.githubusercontent.com/8709019/69915907-a833d900-1454-11ea-96f3-ef5015076b0e.JPG)

Windows 10.

**Comment by doom-fr** [comment]
Right click on the component and choose "snap to the grid"

**Comment by petus** [comment]
OK, goog point. Thanks, but it doesn't make sense to do it with each component

**Comment by doom-fr** [comment]
Yes. This can be an improvement to add a snap grid to components that are selected
