### ISSUE TITLE
Application interface's strings are appear in the wrong language

### ISSUE THREAD

**Issue by EdizonTN** [LibrePCB/LibrePCB#611]
##### VERSION / OS / ENVIRONMENT
LibrePCB Version: 0.1.3
Git Revision:     56bc60d347ff67df0fe1d57807d03f0606de557f
Build Date:       2019-11-30T21:59:40
Qt Version:       5.11.3 (built against 5.11.3)
CPU Architecture: x86_64
Operating System: Windows 7 SP 1 (6.1)
Platform Plugin:  windows

##### SUMMARY
The application interface's strings are shown based on the OS System language settings. Libre PCB Workspace language settings are ignored (mostly).

##### STEPS TO REPRODUCE
OS Windows 7:
Change Regional settings to Slovak:
1. Click the Start button, and then click Control Panel.
2. Click Clock, Language, and Region, and then click Regional and Language Options.
3. The Regional and Language Options dialog box appears. Change Format combo list value to **Slovak**.
![Lang_SysControlPanel](https://user-images.githubusercontent.com/48570749/69919361-45563800-147c-11ea-8995-ba8ff448f666.png)

Now Start LibrePCB. Change Workspace setting -> Application Language to **English** and restart Libre PCB.

##### EXPECTED RESULTS
Of course, I should see interface strings, which depends on the workspace setting. 

##### ACTUAL RESULTS
![Lang_WorkspaceSettings](https://user-images.githubusercontent.com/48570749/69919356-3bccd000-147c-11ea-914c-dd4d4e7e1cb9.png)

You can see result - some string are in Slovak (Most of them) - depends on OS's Regional settings and some in English (few strings) - depends on workspace setting. 
Check also PCB Editor, Schematic Editor and Library Editor. 
I think all strings are in Slovak - by OS Regional settings.

**Comment by ubruhin** [comment]
Yeah I also noticed that some time ago... This happens because we always set the system language as fallback language for strings which aren't available in the language chosen in workspace settings. And since English contains almost no translations (it's the source language, so we don't need translations for it), most of the strings will fall back to the system language :(
