### ISSUE TITLE
Board editor: Don't remove complete trace when changing device

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#616]
##### SUMMARY
When you change of device in the board (right click -> change device), it deletes all traces connected to the device, including vias and goes far.
When it is a integrated circuit with also gnd and vcc, it suppresses a lot of things.

##### SOLUTION
Just delete the last segment of each trace connected to the device.
If the user needs more suppression, he will do it by hand with "remove trace" or "remove segment".

**Comment by dbrgn** [comment]
I agree with this feature request.

Workaround: Manually delete the trace segments that connect the device before removing it.
