### ISSUE TITLE
Same «429 commits to master since this release» for any releases since v0.1.0-rc1

### ISSUE THREAD

**Issue by Symbian9** [LibrePCB/LibrePCB#619]
##### SUMMARY

Commit count in GitHub releases summaries incorrect

- https://github.com/LibrePCB/LibrePCB/releases/

##### EXPECTED RESULTS

Each release summary should represent real count of commits to `master` since each release.

##### ACTUAL RESULTS

Any release summary (since `v0.1.0-rc1`) has same count of commits: *«429 commits to `master` since this release»*

**Comment by dbrgn** [comment]
That's because of the [release workflow with a separate release branch](https://developers.librepcb.org/da/dbc/doc_release_workflow.html).
