### ISSUE TITLE
Add formulas for LibrePCB on homebrew-core and homebrew-cask

### ISSUE THREAD

**Issue by luzpaz** [LibrePCB/LibrePCB#626]
https://github.com/Homebrew/homebrew-core  
https://github.com/Homebrew/homebrew-cask

**Comment by dbrgn** [comment]
None of the developers uses macOS, so a community-maintained formula would be welcome! 🙂

**Comment by ubruhin** [comment]
In the mean time someone added a Homebrew Cask package for LibrePCB so we can close this! :tada:

https://formulae.brew.sh/cask/librepcb
