### ISSUE TITLE
Add LibrePCB to wikipedia

### ISSUE THREAD

**Issue by luzpaz** [LibrePCB/LibrePCB#627]
No representation on https://en.wikipedia.org/wiki/Comparison_of_EDA_software

**Comment by dbrgn** [comment]
Thanks @doom-fr for adding LibrePCB!

**Comment by doom-fr** [comment]
Yes, I have done this !
But if someone than knows the project better than me can check what I have written, it might be a good idea.
I have added LibrePCB in the two tables (I don't know exactly why there's two).

And the problem is that we need now to add a page for LibrePCB ... :-)

**Comment by doom-fr** [comment]
I just received this : 

> Hello. Your recent edit to Comparison of EDA software appears to have added the name of a non-notable entity to a list that normally includes only notable entries. In general, a person, organization or product added to a list should have a pre-existing article before being added to most lists. If you wish to create such an article, please first confirm that the subject qualifies for a separate, stand-alone article according to Wikipedia's notability guideline. See also WP:COI, in case it applies. 

So the point is not closed ...

I try to add a first version for LibrePCB page.

**Comment by dbrgn** [comment]
Cool, thanks! Generally it's considered best-practice on Wikipedia if the authors of a project don't add a WP page themselves, so it's great if you can start something.

The notability guidelines can be found here: https://en.wikipedia.org/wiki/Wikipedia:Notability I'm not sure if LibrePCB qualifies yet, but here is some independent third party coverage that might help, in case it's being disputed:

- Sourcesort interview: https://www.sourcesort.com/interview/urban-bruhin-librepcb
- Adafruit blog picking up the interview: https://blog.adafruit.com/2019/10/31/creating-a-foss-printed-circuit-board-design-tool-opensource-librepcb/
- Blogpost about the new release in a Spanish Linux community blog: https://www.linuxadictos.com/liberada-la-nueva-version-del-software-de-diseno-de-pcb-librepcb-0-1-3.html

The fact that the project received a presentation slot at FOSDEM 2018 and 2020 might also help.

**Comment by doom-fr** [comment]
Yes, I am answering that. Thanks for some links I do not know.

Le dim. 8 déc. 2019 à 23:03, Danilo Bargen <notifications@github.com> a
écrit :

**Comment by doom-fr** [comment]
Can I also say : 

> LibrePCB output file format is also supported by Aisler, a main PCB manufacturer : https://twitter.com/AislerHQ/status/1203305615096979456?s=20

(I really do not know the size of Aisler)

**Comment by dbrgn** [comment]
Yes, that surely helps with regard to notability.

**Comment by dbrgn** [comment]
Further coverage that can help:

- [Hackaday review](https://hackaday.com/2023/10/03/review-librepcb-hits-version-1-0/) (2023)
- [Heise review](https://www.heise.de/news/Open-Source-Leiterplatten-LibrePCB-Version-1-0-0-9528358.html)
- [Golem review](https://www.golem.de/news/librepcb-freie-software-fuer-pcb-design-erreicht-version-1-0-2309-178019.html) (2023)
- [electronicsforu.com post](https://www.electronicsforu.com/technology-trends/librepcb-an-open-eda-built-for-makers-and-engineers) (2025)
- [FOSDEM 2026 Talk](https://fosdem.org/2026/schedule/event/DFBYLP-librepcb-2_0/)
- [NLNet Foundation Listing](https://nlnet.nl/project/LibrePCB2.0/)
