### ISSUE TITLE
Travis CI: Mac builds are broken

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#63]
No idea why, but mac builds are failing with this error message:
```Project ERROR: Unknown module(s) in QT: webkitwidgets```

**Comment by ubruhin** [comment]
As I don't have a mac, I can't reproduce this error locally. It would be great if a mac user could fix this issue ;)

Until this issue is solved, mac builds are allowed to fail (see #66).

**Comment by ubruhin** [comment]
@HBadertscher Maybe you could fix this issue? :smile:

**Comment by HBadertscher** [comment]
I'll have to come over to Coredump some time, probably next monday. I will then look into this issue, ok?

**Comment by ubruhin** [comment]
Fantastic! :+1:
