### ISSUE TITLE
Library editor: Allow filtering elements in overview widget

### ISSUE THREAD

**Issue by sixtyfive** [LibrePCB/LibrePCB#665]
All 6 of the multiple-select widget in the library editor's browser screen can grow to quite large numbers, making it less than entertaining to find something by scrolling and keeping the alphabetical order in mind. It would be great if each of them could get a simple filter (start typing, list gets shorter as you type–one of those) above it.

**Comment by ouabache** [comment]
I would like to see detachable windows that can be resized or even disabled
if not needed.
