### ISSUE TITLE
Schematic Editor: Pages disappear in dock widget

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#681]
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 0.1.4-unstable
Git Revision:     16bdf52a7aabdb4830a771d911f89d0c79c5a374
Build Date:       2020-01-08T19:13:29
Qt Version:       5.12.3 (built against 5.12.3)
CPU Architecture: x86_64
Operating System: Ubuntu 18.04.4 LTS
Platform Plugin:  xcb
```

and also in last nightly build

```
LibrePCB Version: 0.2.0-unstable
Git Revision:     22960e3f2410972903ee06a7f5ae99c2faa88734
Build Date:       2020-03-28T11:32:59
Qt Version:       5.12.3 (built against 5.12.3)
CPU Architecture: x86_64
Operating System: Ubuntu 18.04.4 LTS
Platform Plugin:  xcb
```

##### SUMMARY
I open a project and one page of schematic is missing.
It was the last one

##### STEPS TO REPRODUCE
1. open a project
2. look at the list of page

##### EXPECTED RESULTS
3 pages

##### ACTUAL RESULTS
2 pages
![image](https://user-images.githubusercontent.com/7809481/78055032-3d06fe80-7383-11ea-88b2-67d8a3f00d9f.png)

##### ADDITIONAL INFORMATION
The files seems to be there : 
![image](https://user-images.githubusercontent.com/7809481/78055319-aab32a80-7383-11ea-8817-67f86c289cb2.png)

content of `schematics/schematic.lp`
```
(librepcb_schematics
 (schematic "schematics/schematic/schematic.lp")
 (schematic "schematics/schematic_p2/schematic.lp")
 (schematic "schematics/schematic_p3/schematic.lp")
)
```

**Comment by doom-fr** [comment]
```
[DEBUG-MSG] load project library... (:0)
[DEBUG-MSG] successfully loaded 56 symbols (:0)
[DEBUG-MSG] successfully loaded 45 packages (:0)
[DEBUG-MSG] successfully loaded 46 components (:0)
[DEBUG-MSG] successfully loaded 53 devices (:0)
[DEBUG-MSG] project library successfully loaded! (:0)
[DEBUG-MSG] load circuit... (:0)
[DEBUG-MSG] circuit successfully loaded! (:0)
[DEBUG-MSG] 3 schematics successfully loaded! (:0)
```

3 schematics !!!

What I also want to add is that I have fully reinstalled my PC (ubuntu 18.04 LTS) some weeks ago.
But I have all files !

**Comment by doom-fr** [comment]
And if I add a new schematic page, it appears back !
but new save does not change the problem

**Comment by doom-fr** [comment]
Found !
In fact, there was a problem of display of the previews (miniatures).
If you change the size of the column, it appears back, and then all is ok.

**Comment by ubruhin** [comment]
Indeed, I was able to reproduce this issue! It seems that sometimes pages are wrapped into a second column and might not be visible at all, depending on the dock width:

![grafik](https://user-images.githubusercontent.com/5374821/78724980-cfcd0d80-792e-11ea-90a7-8039c837aaa8.png)
