### ISSUE TITLE
Schematic Editor: Component toolbar does not respect configured norm

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#697]
##### SUMMARY

The "Add Component" toolbar in the schematic editor always shows and adds IEC symbols, no matter what preferred norm is configured in workspace settings. That's annoying for people using the IEEE 315 norm. See [this discussion](https://librepcb.discourse.group/t/how-do-i-add-ieee-315-to-my-preferences/88/8) in the forum.

##### SOLUTION

- [ ] Display toolbar symbols according configured norm
- [ ] When adding components, choose the symbol variant which corresponds to the configured norm

Some day we might want to make this toolbar fully configurable anyway (something like "favorite components", configurable in the workspace settings), but having norm-aware, hardcoded components is at least much better than the current situation, and probably does not need any file format change.

**Comment by hooperbloob** [comment]
Reviewed the code with the hard-coded references.  For a later release a better solution would have all those references externalized to a config file named after chosen norm. Users could then revise the chosen components, voila - customizable toolbars.
