### ISSUE TITLE
Library Editor: Placement / documentation colors too similar

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#707]
##### SUMMARY
Top placement and (Top) Documentation are too main layers used when you create a package.
But colors are quite the same, so often bad layer is used.
To fix this, the user should change all bad layer items.
This need sometime to move already placed objects because of https://github.com/LibrePCB/LibrePCB/issues/536

##### SOLUTION
change colors to make a real difference.
And fix #536 :-)

**Comment by dbrgn** [comment]
I agree! Do you have a concrete proposal for colors to be used?

**Comment by doom-fr** [comment]
Not easy !

Here is a proposition (on left actual, on right new) : 

![image](https://user-images.githubusercontent.com/7809481/83572751-69c5c680-a52a-11ea-9f8a-d046de70d69b.png)

**Comment by dbrgn** [comment]
That doesn't look too bad actually! @ubruhin what do you think?

@doom-fr what color value did you use here?

**Comment by dbrgn** [comment]
Ah, you used image editing... I thought you changed the colors in your config file (`boards/default/settings.user.lp`, see https://github.com/LibrePCB/LibrePCB/issues/406).

You can find the default colors in `libs/librepcb/common/graphics/graphicslayer.cpp`.

**Comment by doom-fr** [comment]
With `#76fbc697` for top documentation

![image](https://user-images.githubusercontent.com/7809481/83956542-939b2800-a85f-11ea-92c7-8d8ebecc8439.png)

**Comment by doom-fr** [comment]
And the problem is mainly in the Library editor and not in the Board editor.
(even if I think both should have same colors)

**Comment by doom-fr** [comment]
Maybe it was also a good idea to set top documentation as default layer in Library editor and not top placement, as we start by drawing the component and in second time draw the placement.
