### ISSUE TITLE
Board Editor : Bad net name displayed

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#712]
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 0.1.4
Git Revision:     ae04eef5a71b5ba66ae2cee6b631c1c933ace535
Build Date:       2020-05-02T18:50:04
Qt Version:       5.14.2 (built against 5.14.2)
CPU Architecture: x86_64
Operating System: Ubuntu 18.04.4 LTS
Platform Plugin:  xcb
```

##### SUMMARY
Net name displayed is not the good one
(But air wiring seems to be good)

##### STEPS TO REPRODUCE
Maybe change net of this pin

##### EXPECTED RESULTS
Show the good name

##### ACTUAL RESULTS
Show the bad name

![Bug net LibrePCB](https://user-images.githubusercontent.com/7809481/83952947-e9aaa400-a83c-11ea-91f8-53069fba965d.gif)

**Comment by doom-fr** [comment]
close & launch the Board Editor does not solve the problem.
close & open the project solve the problem

**Comment by ubruhin** [comment]
Yes, I guess when renaming a net, the rename is not propagated to all graphical elements on the board and thus outdated net names are shown.

**Comment by doom-fr** [comment]
For information, seems there's quite same problem on via.

![image](https://user-images.githubusercontent.com/7809481/83978186-14146400-a906-11ea-9c8f-2b7bde02cfa1.png)

Quite same, but not sure related as I've just placed the via 5s before.
