### ISSUE TITLE
FR: When copy-pasting package, keep pin assignments

### ISSUE THREAD

**Issue by sixtyfive** [LibrePCB/LibrePCB#717]
Example:

- user creates new package QFN-32 with pins 1..32 and Thermal_Pad
- then opens existing package QFP-32, selects, and copies everything
- now pastes into new (and thus far, empty) package

Result at the moment:

The new package will have 32 pads, with only a 33rd needing to be added for the thermal pad. But none of the pads is assigned to any of the signals; assignment has to be done manually, even though it is non-ambiguous.

Desired result:

Upon pasting, LibrePCB noticed that 32 of the 33 signals' names match with 32 of the 32 pads' previously assigned signals and restores those assignments.

**Comment by ubruhin** [comment]
This has been fixed in #807 so it will be shipped with LibrePCB 0.2.0 :muscle:
