### ISSUE TITLE
The current IEEE 315 resistor symbol should only have 3 points on each side, not 4

### ISSUE THREAD

**Issue by hooperbloob** [LibrePCB/LibrePCB#725]
Have a look at the common results here:

https://duckduckgo.com/?q=iee315+resistor+symbol&t=chromentp&iax=images&ia=images

http://www.resistorguide.com/resistor-symbols/

While there are a few shown with four points per side, the majority show just three.

**Comment by dbrgn** [comment]
Thanks for bringing this up!

This issue probably belongs in https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib, but it seems I can't move issues between different organizations.

@hooperbloob maybe you could re-open your issue at https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/issues?
