### ISSUE TITLE
Board Editor: Pad text upside down for rotated parts.

### ISSUE THREAD

**Issue by 5n8ke** [LibrePCB/LibrePCB#732]
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 0.1.4
Git Revision:     ae04eef5a71b5ba66ae2cee6b631c1c933ace535
Build Date:       2020-05-02T18:50:43
Qt Version:       5.11.3 (built against 5.11.3)
CPU Architecture: x86_64
Operating System: Windows 10 (10.0)
Platform Plugin:  windows
```

##### SUMMARY
The text on a pad, which is pin number and net name, is rotated with the device. This results in sideways or upside-down text, making it less readable

##### STEPS TO REPRODUCE
Add a device to a PCB, rotate the device by an arbitrary amount.

##### EXPECTED RESULTS
The text on the pad is in the standard text orientation.

##### ACTUAL RESULTS
The text keeps its position relative to the device, resulting in a skewed or upside-down text.
![Pad text](https://user-images.githubusercontent.com/6875541/87243836-81ea0900-c439-11ea-9120-0638d2de3ed8.png)

##### ADDITIONAL INFORMATION
Related to #580 which concerns cut-off text on the pads.

**Comment by ubruhin** [comment]
This has been fixed in #1136, pad texts are now always displayed with 0° rotation :muscle:
