### ISSUE TITLE
The workspace cannot be opened after library edit or crash

### ISSUE THREAD

**Issue by miniwark** [LibrePCB/LibrePCB#734]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.4 from Flathub
Git Revision:
Qt Version:
Operating System: Linux Manjaro (Arch)
...
```

##### SUMMARY

When starting the application i get the following message, even after a reboot:

> The workspace "/home/miniwark/Documents/Developpements/PCB/LibrePCB" cannot be opened: The workspace is already opened by another application instance or user!

The LibrePCB just quit. (may be related to #154)

##### STEPS TO REPRODUCE

It had happen randomly times already. I think it's related to crash and/or bad saves during local Library editing (but a also have the case without crashes).

I suspect than there is a temporary file somewhere (instead of a PID) who keep track of open library parts, but who is not correctly deleted.

##### EXPECTED RESULTS

LibrePCB must offer me a way to try to force my way after the warning instead of just quitting.

**Comment by miniwark** [comment]
(as a workaround can you tel me witch file to delete instead of recreate / re-downloard libraries ?)

**Comment by ubruhin** [comment]
Actually the lock should be ignored if the process which created the lock is no longer running. This might not work if for example the PID could not be determined. Could you post the content of your `LibrePCB-Workspace/v0.1/.lock` file (feel free to obfuscate username etc.)?

**Comment by miniwark** [comment]
@ubruhin, sure:

```
Username
username
mycomputer
2
librepcb
2020-07-19T09:18:55Z
```

**Comment by ubruhin** [comment]
Thanks! It looks good, but the PID `2` looks strange, which helped me to find the actual problem: It seems that Flatpak uses PID namespacing, thus LibrePCB probably still has PID=2 after a crash, therefore the file lock cannot be considered as stale. See also https://github.com/flatpak/flatpak/issues/1963. I'm not sure if we can do anything to fix this, I suspect detecting stale file locks in a reliable way is impossible if PIDs are namespaced :(

> LibrePCB must offer me a way to try to force my way after the warning instead of just quitting.

Yeah, probably it's the only workaround to provide a way to ignore the file lock, with the risk that users ignore file locks by accident which possibly leads to much more serious issues like corrupt projects and workspaces. I'm not sure if we should provide such a dangerous option... Or at least only provide it if the PID is "suspect" (<10 or so).

**Comment by miniwark** [comment]
Or maybe use the file timestamp for the "force option" ?

**Comment by kilt-er** [comment]
I am having this same problem.  If I delete the PID line, then I can start the program.  However, when I go to open my project, I get:

"The directory is locked, check if it is already opened elsewhere: [project]"

What should I do?

**Comment by kilt-er** [comment]
I managed to find two more .lock files.  I did the sam PID clear, and I was able to get myself unblocked after an hour-and-a-half of freaking out.

Wondering if there is anything that can be done here to more accurately determine when a lock has been involved in a crash and clear it.

**Comment by miniwark** [comment]
@kilt-er in my case, for a workaround, i have simply deleted the `.lock` file in the library instead of editing it (because i was sure than i have only one LibrePCB running).

**Comment by kilt-er** [comment]
> @kilt-er in my case, for a workaround, i have simply deleted the `.lock` file in the library instead of editing it (because i was sure than i have only one LibrePCB running).

Thanks for the info.  I tried that and it led to a different error message about the lock file being missing.  The lock is held after reboot -- no multiple instance concerns.  It seems like legit bug that the program would fail to recognize a lock held in error after crash when only one instance is running.

**Comment by ubruhin** [comment]
@kilt-er Did you install LibrePCB with Flatpak? If not, which operating system are you using?

**Comment by kilt-er** [comment]
Ah, sorry for leaving that out.  Yes, I'm using Flatpak on the latest Rasbian OS for Rpi 4

**Comment by ubruhin** [comment]
OK so the main problem is that the same PID gets reused because Flatpak uses PID namespacing, and thus LibrePCB thinks the application holding the lock is still running.
