### ISSUE TITLE
Schematic Editor : Raise a warning if one net is connected to only one pin

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#739]
##### SUMMARY
I usually use nets to connect pins in schematic to make it more clear.
Unfortunately, there's a risk to miss an unconnected net.
(unfortunately, I experienced that !)

##### SOLUTION
Raise a warning if one net is connected to only one pin.

**Comment by ubruhin** [comment]
Hmm I don't understand, actually the ERC already raises a warning in this case:

![grafik](https://user-images.githubusercontent.com/5374821/89098313-b7559700-d3e6-11ea-93a7-18fc60c3ce31.png)

Or what do you mean exactly?

**Comment by doom-fr** [comment]
Unfortunately, I use a 'schematic only' component to set the net : 

![image](https://user-images.githubusercontent.com/7809481/89102890-ba17b280-d40d-11ea-992e-9602978eb258.png)

And like that, it does not raise eror or warning.
So I think that 'schematic only' component should not be counted as real connection !

PS : maybe you can also add connection port(s) as native in LibrePCB  ![image](https://user-images.githubusercontent.com/7809481/89102987-8ee19300-d40e-11ea-9a32-dd8d544c7700.png)

(I know, this should be in another issue !)

**Comment by dbrgn** [comment]
Hm, why don't you just set the net using a net label?

**Comment by doom-fr** [comment]
It's more clear if it was input, output or input/output (I have the 3 variants), and I found it more visible.
And I used it before in Protel !

**Comment by 5n8ke** [comment]
Ignoring schematic-only devices for determining, whether a signal is connected to more than one pin, would also show a warning when only one pin is connected to a VCC or GND device. This is especially useful when having multiple different supply voltages.

**Comment by doom-fr** [comment]
??
Sorry but do not understand your argument.
I even found that this reinforced my position for this issue !

As this kind of schematics makes no sense but do not raise error/warning : 
(here R1 is in fact connected to anything ... (place the device on the board and you will see))

![image](https://user-images.githubusercontent.com/7809481/89110927-582c6c80-d450-11ea-93d7-6ae652d4ce91.png)

**Comment by doom-fr** [comment]
> Ignoring schematic-only devices for determining, whether a signal is connected to more than one pin, would also show a warning when only one pin is connected to a VCC or GND device. This is especially useful when having multiple different supply voltages.

??
Sorry but do not understand your argument.
I even found that this reinforced my position for this issue !

As this kind of schematics makes no sense but do not raise error/warning : 
(here R1 is in fact connected to anything ... (place the device on the board and you will see))

![image](https://user-images.githubusercontent.com/7809481/89110927-582c6c80-d450-11ea-93d7-6ae652d4ce91.png)

**Comment by 5n8ke** [comment]
> ??
> Sorry but do not understand your argument.
> I even found that this reinforced my position for this issue !
> 
> As this kind of schematics makes no sense but do not raise error/warning : 
> (here R1 is in fact connected to anything ... (place the device on the board and you will see))

Exactly my point! I was making an argument for changing the current behavior.

Currently schematic-only devices are not ignored, when determining the count of connected pins to a NetSignal

**Comment by doom-fr** [comment]
> Exactly my point! I was making an argument for changing the current behavior.
> Currently schematic-only devices are not ignored, when determining the count of connected pins to a NetSignal
Ok. Sorry. So I just misunderstood what you said.
And so we both agree !
