### ISSUE TITLE
Via cannot be placed on existing node

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#747]
##### VERSION / OS / ENVIRONMENT

Current master:

```
LibrePCB Version: 0.2.0-unstable
Git Revision:     5550e992861257943b60c1cf896c5df4f98842d5
Build Date:       2020-08-02T20:00:18
Linking type:     dynamic
Unbundled libs:   (all) quazip polyclipping fontobene-qt5
Qt Version:       5.15.0 (built against 5.15.0)
CPU Architecture: x86_64
Operating System: Arch Linux
Platform Plugin:  xcb
```

##### STEPS TO REPRODUCE

1. Start drawing trace
2. Create a node
3. Decide to switch layer, type "1"
4. Via placement UI appears
5. Click at the same location
6. Via isn't placed, the wire mode exits

See video: https://tmp.dbrgn.ch/librepcb-2020-08-05_16.44.38.webm

##### EXPECTED RESULTS

It should be possible to place a via on an existing node.

CC @5n8k

**Comment by 5n8ke** [comment]
This is already on my TODO for the next iteration of the tool. I want to wait with this addition until the via placement tool is a little bit more refined.

https://github.com/LibrePCB/LibrePCB/blob/745237a716a6461224385f68be7f2abe816dda2c/libs/librepcb/projecteditor/boardeditor/fsm/bes_drawtrace.cpp#L638
