### ISSUE TITLE
Incremental Search in Library List

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#780]
### SUMMARY

In the library manager, when having a lot of libraries installed, it would be nice if the user could jump to the desired library by clicking into the library list and starting to type (with incremental search). (I think this would be better than a filter because it feels more natural.)

##### SOLUTION

I took a look at how this could be implemented. On the library list, an event filter can be installed:

```c++
bool LibraryManager::eventFilter(QObject *obj, QEvent *event) noexcept {
    if (event->type() == QEvent::KeyPress) {
        QKeyEvent *keyEvent = static_cast<QKeyEvent *>(event);
        qDebug("Handle key %d", keyEvent->key());
        return true;
    } else {
        // standard event processing
        return QObject::eventFilter(obj, event);
    }
}
```

```c++
mUi->lstLibraries->installEventFilter(this);
```

I would add a nullable `searchTerm` string field to the library manager class. When starting to type, every keypress would append the key to that search term. Every time the search term changes, the code would iterate the list and highlight the matching search term (using rich text functionality in the library list widget item). If the currently selected item is not part of the highlighted group, the selection would jump to the next item found. Pressing ESC would clear the search term and reset search term highlighting.

Does that sound like a good plan?

**Comment by ubruhin** [comment]
Makes sense, but regarding the implementation it sounds quite hacky ;) Actually jumping to items in a QListWidget usually works out of the box as far as I remember. If it doesn't work for the library list, it might be caused by our custom item widgets. In that case I suspect there would be a simple solution (maybe we just need to set the item titles or something like that).
