### ISSUE TITLE
Board Editor: Activate "Select" after placing Components

### ISSUE THREAD

**Issue by hexa6six** [LibrePCB/LibrePCB#787]
##### SUMMARY
While placing the components on the board one sometimes has to relocate other components or the component itself. But the select mode is deactivated after placing a component, so one always has to use the mouse to switch into select mode manually. This breaks the workflow at this point.

##### SOLUTION
After placing a component, the select mode should be activated. 

Best regards,
Harry

**Comment by ubruhin** [comment]
Thanks for reporting this! #794 will fix this for the next release.
