### ISSUE TITLE
Get rid of QtWebKit

### ISSUE THREAD

**Issue by The-Compiler** [LibrePCB/LibrePCB#79]
QtWebKit got removed upstream with Qt 5.6 - if you still need a HTML viewer after #72 I'd recommend either QtWebKit or QtWebEngine via a compile-time flag, or using something more minimalistic like [QTextBrowser](http://doc.qt.io/qt-5/qtextbrowser.html) which has some degree of HTML support.

**Comment by ubruhin** [comment]
Merged #87
