### ISSUE TITLE
Invalid UUID when confirming in properties window

### ISSUE THREAD

**Issue by AvianY** [LibrePCB/LibrePCB#801]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.5
Git Revision: a435c5095c
Qt Version: 5.15.0
Operating System: Windows 10
...
```

##### SUMMARY

I get the error message "string is invalid UUID" when I click on OK or APPLY in the pad properties window in the Package designer.

**Comment by ubruhin** [comment]
Thanks! This is a duplicate of #641.
