### ISSUE TITLE
Inconsistent Plane Operation and Add Vertex to Plane Not Available

### ISSUE THREAD

**Issue by brim2full** [LibrePCB/LibrePCB#828]
##### VERSION / OS / ENVIRONMENT
LibrePCB Version: 0.1.5
Git Revision:     a435c5095c6f94df4da130fe832ea97f42d17901
Build Date:       2020-10-03T20:06:07
Linking type:     static
Unbundled libs:   -
Qt Version:       5.15.0 (built against 5.15.0)
CPU Architecture: x86_64
Operating System: Windows 10 Version 2009
Platform Plugin:  windows

##### SUMMARY
1) There is at least one edge of an plane that it is impossible to add a new vertex to.
2) There is a difference between the Add Plane function on start up (no nets defined) and when all nets have been deleted.

##### STEPS TO REPRODUCE

    

1.     Create a new project.
2.     Add capacitor and a ground symbol. Connect them in the circuit diagram.
3.     Placed on the board but not routed.
4.     Add Plane functions. (Signal = GND, Layer=Top Copper)
5.     Draw a rectangle starting top left then top right, next bottom right finally bottom left.
6.     Select the arrow tool.
7.     Click on each line in turn to show pop-up selection and that “Add Vertex”. Should fail on left hand line. (BUG: Unable to add vertex to plane.)
8.     Delete components from the board and circuit.
9.     Add Plane shows parameters but reports “Logic Error” when trying to draw a plane. Note Signal Property is blank and no other selection is available. (BUG: Inconsistent functionally. When a new project is created this function is disabled.)
10.     Re-create the previous capacitor and GND circuit.
11.     Go to the board editor. Add the capacitor to the board.
12.     Select Add Plane and ensure the Signal is GND also change the Layer to the Bottom Copper.
13.     Trying to add a plane fails reporting “Logic Error”.
14.     Change the Layer to Top Copper and retry Add Plane also fails with “Logic Error”. (BUG: Inconsistent functionality. This worked in step 4.)

##### ADDITIONAL INFORMATION
It would also be helpful to have a more user orientated Error message at step 13.  Something like: "Plane cannot be added due to the absence of defined nets."

**Comment by doom-fr** [comment]
Yes, the last edge of a plane can't be used to add a new vertex.
