### ISSUE TITLE
Recent projects colour is hard to read

### ISSUE THREAD

**Issue by na-sa-do** [LibrePCB/LibrePCB#834]
##### VERSION / OS / ENVIRONMENT
Version: 0.1.5
Git revision: a435c5095c
Build date: 2020-10-03 19:48:36 (CST)
Qt version: 5.14.2
OS: Arch Linux (KDE, Breeze Dark)

##### SUMMARY
The recent projects list uses a dark blue that is very hard to read on dark backgrounds.

##### STEPS TO REPRODUCE
Switch to a dark Qt theme and open the control panel.

##### EXPECTED RESULTS
The list should use a theme-configured colour.

##### ACTUAL RESULTS
I think the form is a little overkill for this particular bug.

**Comment by halfshavedyaks** [comment]
I have this issue with the MacOS dark theme too.
