### ISSUE TITLE
Library Editor : Cannot place bottom pad at same position of top pad

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#836]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.5
Git Revision:     a435c5095c6f94df4da130fe832ea97f42d17901
Build Date:       2020-10-03T19:48:36
Linking type:     static
Unbundled libs:   -
Qt Version:       5.14.2 (built against 5.14.2)
CPU Architecture: x86_64
Operating System: Ubuntu 20.10
Platform Plugin:  xcb
```

##### SUMMARY
It seems to be impossible to place bottom pad at the same position of top pad in Library Editor

##### STEPS TO REPRODUCE

1. create a new footprint
2. place a pad on the top
3. click on the blue icon to select bottom
4. place a bottom pad at same position
   => can't place it

##### EXPECTED RESULTS
The pad is placed on bottom

##### ACTUAL RESULTS
The pad can't be placed at this position, but it is possible at other positions.

##### ADDITIONAL INFORMATION
workaround, place the pad at another position and move it to the good position.

**Comment by dbrgn** [comment]
Confirmed!

**Comment by doom-fr** [comment]
In fact the problem is not a problem of layer.
It is also impossible to put a top pad on top of another just placed top pad.

But if you deselect the pad tool and restart it, it works (whatever the layer is).
