### ISSUE TITLE
Gerber : Mysterious message "Value must be > 0 !"

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#838]
##### SUMMARY

![image](https://user-images.githubusercontent.com/7809481/105995941-f4ef6000-60a9-11eb-9ff4-231e8f3f6e71.png)

"Value must be > 0 !" => Which value ?
(think it was hole size)

##### SOLUTION
Display a more specific message : tell the value that need to be >0

**Comment by ubruhin** [comment]
The error comes from a very low level class which doesn't "know" what it is used for (could be a hole diameter, trace width, line length, ...) thus it's hard to say where the actual error is located... But yeah, most probably there is some hole with a diameter <=0. Can you confirm that? And do you have an idea how it was possible to create such an invalid object (it should actually not be possible)?

**Comment by doom-fr** [comment]
Yes it is related to #839 !

**Comment by ubruhin** [comment]
I think with the refactoring done in #1076 this invalid case can no longer exist. Holes with a diameter of 0mm will be removed during the file format migration 0.1->0.2 and cannot be created anymore with 0.2.x. So let's close this issue.
