### ISSUE TITLE
Library Editor : THT without hole

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#839]
##### SUMMARY
![image](https://user-images.githubusercontent.com/7809481/105996464-a5f5fa80-60aa-11eb-80d5-29ab14fd3a5f.png)

What's the way to place top and bottom pad without hole ?

When we put hole size = 0mm, DRC warns and gerber generation report an error.

Placing a top and a bottom pad is possible but it would be better to have another option.

##### SOLUTION

Manage 0mm hole size as "no hole" or add a "no hole" option.

**Comment by dbrgn** [comment]
A through-hole pad without a hole is arguably not a through-hole pad.

Why don't you add two SMD pads, one on top and one at the bottom?

**Comment by doom-fr** [comment]
Obviously I tried, but it is more difficult.
And I encounter two bugs (#836 & #840), so really not easy.

If it is not allowed to do THT with zero size hole, we need to prevent to do it.

**Comment by dbrgn** [comment]
Yes, that's true, the drill diameter should not allow 0 to be entered!

**Comment by ubruhin** [comment]
This is actually fixed with #1076 which refactored the concept of pad holes :muscle:
