### ISSUE TITLE
Board Editor : click two times on 'Add' button of 'Place devices' produce an error

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#850]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.5
Git Revision:     a435c5095c6f94df4da130fe832ea97f42d17901
Build Date:       2020-10-03T19:48:36
Linking type:     static
Unbundled libs:   -
Qt Version:       5.14.2 (built against 5.14.2)
CPU Architecture: x86_64
Operating System: Ubuntu 20.10
Platform Plugin:  xcb
```

##### SUMMARY
When placing components in the Board Editor, if we click two times on 'Add' button, it produce an error : 

![image](https://user-images.githubusercontent.com/7809481/107272270-b8c6e280-6a4d-11eb-9917-4ddcbb1d8b57.png)

##### STEPS TO REPRODUCE

1. Go to place devices panel
2. click on 'Add'
3. click on 'Add' => this produce an error

##### EXPECTED RESULTS

Nothing

##### ACTUAL RESULTS

Error

**Comment by ubruhin** [comment]
Seems this has been fixed, at least I can't reproduce it with LibrePCB 0.1.7 :see_no_evil:
