### ISSUE TITLE
Board Editor: Allow partial DRC checking

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#869]
##### SUMMARY

DRC checking is a bit long as it checks a lot of things.
(on my current board, more than 40s with a recent laptop)
It will be great to check only what the user needs at the current moment to speed up the process.

##### SOLUTION

On the left of each line of rules, add a checkbox to validate/invalidate this rule checking.
Add also "activate all rules" and "deactivate all rules" buttons.

**Comment by doom-fr** [comment]
It will be great also if there's the possibility to check only already found errors.

**Comment by ubruhin** [comment]
Implemented in #907, any feedback welcome :slightly_smiling_face: 

> It will be great also if there's the possibility to check only already found errors.

Although that would indeed be nice, currently it would be very difficult to implement - not worth the effort I think. Thus I didn't implement this yet.
