### ISSUE TITLE
Gerber Generation : "Invalid coincident draw" error on Ucamco gerber viewer

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#870]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.5
Git Revision:     a435c5095c6f94df4da130fe832ea97f42d17901
Build Date:       2020-10-03T19:48:36
Linking type:     static
Unbundled libs:   -
Qt Version:       5.14.2 (built against 5.14.2)
CPU Architecture: x86_64
Operating System: Ubuntu 20.10
Platform Plugin:  xcb
```

##### SUMMARY

In some conditions, the generated Gerber files can't be correctly read by the Ucamco Gerber viewer https://gerber-viewer.ucamco.com/
Is seems to be related to cut-out in planes.

##### STEPS TO REPRODUCE

1. generate gerber file and  upload in Ucamco viewer

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/7809481/109433727-2ee9b400-7a12-11eb-950a-4db3ecc1ee64.png)

###### Error case : 

![image](https://user-images.githubusercontent.com/7809481/109433617-95220700-7a11-11eb-83a7-98508190fad2.png)

###### Good case :

![image](https://user-images.githubusercontent.com/7809481/109433693-fc3fbb80-7a11-11eb-9437-0169ce840721.png)
 
###### Gerber files

[gerber--prob-cutout-planes.zip](https://github.com/LibrePCB/LibrePCB/files/6057978/gerber--prob-cutout-planes.zip)

**Comment by doom-fr** [comment]
On another layer (inner2) : 

This is good : 
![image](https://user-images.githubusercontent.com/7809481/109436356-57c47600-7a1f-11eb-9017-2dfc7467cb19.png)

And this is bad : 
![image](https://user-images.githubusercontent.com/7809481/109436393-95c19a00-7a1f-11eb-9758-3d07e6ac6ced.png)

![image](https://user-images.githubusercontent.com/7809481/109436420-bd186700-7a1f-11eb-9841-6af8895d50a3.png)



It is on a via, so not J30.

What can be observed is that the via and J30 are very close.

Here are the gerber files : 

[gerber--inner2-planes-prob.zip](https://github.com/LibrePCB/LibrePCB/files/6058181/gerber--inner2-planes-prob.zip)

**Comment by ubruhin** [comment]
Thanks for reporting this! I did not find any issue in your Gerber file, so I asked Ucamco about this problem. They say this warning seems to be triggered by a very short line segment in the Gerber file. But there is nothing wrong with the file, it's an issue of their online viewer. They might fix it one day.

So it's safe to hand over such Gerber file to PCB fabricators :slightly_smiling_face: Let's close this issue since we don't need to take care of this.
