### ISSUE TITLE
Pin Name Spacing Parameter

### ISSUE THREAD

**Issue by brim2full** [LibrePCB/LibrePCB#882]
##### SUMMARY
Library Schematic Symbol Editor:  Separate the pin line length parameter from the pin name distance.  Would eliminate this issue:
![Text Spacing](https://user-images.githubusercontent.com/73645498/113818913-0b7bfc80-9768-11eb-962b-e7e3eb73d31a.PNG)

**Comment by ubruhin** [comment]
Duplicate of #383.
