### ISSUE TITLE
Library Editor : Allow copying object to other library

### ISSUE THREAD

**Issue by khenriks** [LibrePCB/LibrePCB#883]
##### SUMMARY

I'd like to have the ability to easily copy an object (component, device, etc.) from one library to another. I've needed to make tweaks to some of the built-in devices, and this has required moving the device to my own library, then duplicating it, then deleting and re-downloading the base library to restore the original device. It would be nice to have a more straightforward workflow for this.

**Comment by doom-fr** [comment]
related to https://github.com/LibrePCB/LibrePCB/issues/832

**Comment by ubruhin** [comment]
Implemented in #911.
