### ISSUE TITLE
Board Editor: Add DXF import

### ISSUE THREAD

**Issue by jabadabado** [LibrePCB/LibrePCB#891]
Really Great software!

I though when checking it...the most important is here! But then I could not find any way of importing a PCB shape with reference holes via a DXF file etc. Maybe some other way? Through a picture, PDF, or anything that has the exact sizes to begin the board outline and mounting holes etc.

Nowadays, a design begins at the 3D level after hand and mind sketches, designs are no longer based around the PCB. And PCB sizes needs to be imported from that 3D design somehow. The days of square PCB's are long gone.

Jabba

**Comment by ubruhin** [comment]
Hi,

Currently there is no way to import shapes or drills. Either you have to draw them manually, or for very complex shapes it might be worth to create some script to convert DXF to LibrePCB polygons (e.g. using [`librepcb-parts-generator`](https://github.com/LibrePCB/librepcb-parts-generator) which is able to generate such polygons) and then copy them into the `board.lp` file :wink:

But for long term, of course it makes sense to add this feature to the board editor.

**Comment by dryas** [comment]
I just want to add that this is the feature I miss most at the moment. Highly appreciate if we can get some solution here. Thanks for all the great work so far! :-)

**Comment by EdizonTN** [comment]
Please, can you add this feature to the library package editor also? 
Will be great way, how to create complicated footprints and place pads to the right positions (in cooperation with snap function).
