### ISSUE TITLE
Improve CI build time by using ccache

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/LibrePCB#90]
According to https://docs.travis-ci.com/user/caching/#ccache-cache travis supports using ccache, which could speed up builds.

**Comment by ubruhin** [comment]
With merging #91, caching is now working for linux builds with gcc. But with clang and/or osx ccache is not working properly, see issues of travis:
- https://github.com/travis-ci/travis-ci/issues/6201
- https://github.com/travis-ci/travis-ci/issues/5383
- https://github.com/travis-ci/travis-ci/issues/5567

I think I will leave this issue open until these issues are solved...

**Comment by rnestler** [comment]
What can we do on our side to improve the situation? Are there some workarounds?

**Comment by ubruhin** [comment]
I would prefer to just wait some time instead of using an ugly workaround. Maybe this issue gets solved in a few weeks/months, so we don't have to do anything. Leaving this issue open just helps to not forget it ;)
