### ISSUE TITLE
Add thermal relief pads

### ISSUE THREAD

**Issue by dryas** [LibrePCB/LibrePCB#900]
I'm not 100% sure if this is not already possible, but please add a function to use thermal relief pads. Depending on your design it could be very annoying to try to solder something to a pad that is connected to the whole groundplane and act as a big heatsink.

![MkZdx](https://user-images.githubusercontent.com/94088/124836578-7b766a80-df83-11eb-9b53-05103d027370.png)

(normal pad left, thermal relief pad right)

Thanks for all the hard work so far!

**Comment by ubruhin** [comment]
Hi, this is already requested in #454 so I'll close this issue.
