### ISSUE TITLE
Replace private marked copy/default constructors with =delete

### ISSUE THREAD

**Issue by rnestler** [LibrePCB/LibrePCB#93]
In some places in the code the following is found:

``` c++
private:
        // make some methods inaccessible...
        ErcMsgList();
        ErcMsgList(const ErcMsgList& other);
        ErcMsgList& operator=(const ErcMsgList& rhs);
```

Which should be replaced by

``` cpp
public:
        ErcMsgList() = delete;
        ErcMsgList(const ErcMsgList& other) = delete;
        ErcMsgList& operator=(const ErcMsgList& rhs) = delete;
```

The canonical order for the constructors is like follows:

``` cpp
public:
  // Constructors / Destructor
  [Default Constructor]
  [Copy Constructor]
  [Custom Constructors]
  [Destructor]

  // getters, setters, ...

  // Operator Overloadings
  [Assignment Operator]
  [Other Operators]
```

I'm willing to mentor this bug if someone wants to work on it. The following are some of the places were this could be fixed:
- [ ] https://github.com/LibrePCB/LibrePCB/blob/dbc6805ab59c76f2f859ef72f00f24ba047ee2c7/apps/librepcb/controlpanel/controlpanel.h#L124
- [ ] https://github.com/LibrePCB/LibrePCB/blob/340c1bc32e83b2a9852de574c0feec0ff020776d/libs/librepcbworkspace/recentprojectsmodel.h#L59
- [ ] ...

Just search for [`// make some methods inaccessible...`](https://github.com/LibrePCB/LibrePCB/search?utf8=%E2%9C%93&q=make+some+methods+inaccessible&type=Code)

**Comment by ubruhin** [comment]
Yeah, this issue exists in many header files because in the past I have always marked inaccessible methods ```private```. Later I switched to ```delete```, which I always use now when creating new classes...

**Comment by ali-alsabbah** [comment]
I'd like to work on this if mentorship is still available

**Comment by ubruhin** [comment]
> I'd like to work on this if mentorship is still available

Sure, go for it! :smiley:  Just ask either @rnestler or me if you have any questions.

**Comment by rnestler** [comment]
> I'd like to work on this if mentorship is still available

@ali-alsabbah Are you still interested in this? If yes jut tell us how we can support you achieving it :slightly_smiling_face:

**Comment by rzvncj** [comment]
Just browsing here, but wanted to point out that
```c++
public:
        ErcMsgList() = delete;
```
is not really needed, because you already have a user-declared constructor (the copy constructor), so the default constructor will not be generated:

https://en.cppreference.com/w/cpp/language/default_constructor
> _If no user-declared constructors of any kind are provided_ for a class type (struct, class, or union), the compiler will always declare a default constructor as an inline public member of its class.

So what you really need is just:
```c++
public:
        ErcMsgList(const ErcMsgList& other) = delete;
        ErcMsgList& operator=(const ErcMsgList& rhs) = delete;
```

Here's an example:
```c++
class X {

public:
    X(const X&) = delete;
    X& operator=(const X&) = delete;
};

int main()
{
    X x;
}
```
```
$ g++ example.cpp 
constr.cpp: In function ‘int main()’:
constr.cpp:10:7: error: no matching function for call to ‘X::X()’
   10 |     X x;
      |       ^
constr.cpp:4:5: note: candidate: ‘X::X(const X&)’ (deleted)
    4 |     X(const X&) = delete;
      |     ^
constr.cpp:4:5: note:   candidate expects 1 argument, 0 provided
```
