### ISSUE TITLE
CMake: Infinite recursion when finding gtest and gmock

### ISSUE THREAD

**Issue by MorganJamesSmith** [LibrePCB/LibrePCB#933]
I get this error when building. I'm using the compile flag -DUNBUNDLE_GTEST=ON.

I don't understand how cmake works but my guess is line 24 in cmake/FindGTest.cmake where it tried to find_package(Gtest) is actually running the FindGTest.cmake file again. 

```
CMake Error at cmake/FindGTest.cmake:1 (set):
  Maximum recursion depth of 1000 exceeded
Call Stack (most recent call first):
  cmake/FindGTest.cmake:24 (find_package)
  cmake/FindGTest.cmake:24 (find_package)
  cmake/FindGTest.cmake:24 (find_package)
  cmake/FindGTest.cmake:24 (find_package)
  ...
  (lots more of the same here)
  ...
  cmake/FindGTest.cmake:24 (find_package)
  CMakeLists.txt:141 (find_package)
```

**Comment by ubruhin** [comment]
@dbrgn any idea regarding this issue?

**Comment by dbrgn** [comment]
Hi, I had this issue as well when packaging on Arch Linux 😕 During development this worked, so I'm not sure why.

> I don't understand how cmake works but my guess is line 24 in cmake/FindGTest.cmake where it tried to find_package(Gtest) is actually running the FindGTest.cmake file again.

Yeah, I think it's something like that. Probably has to do with how the CMake files bundled with GTest are written.
