### ISSUE TITLE
Board editor : Via drill size can't be greater than via size itself

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#946]
##### SUMMARY
It is possible to make via with drill size greater than the via size itself.

##### SOLUTION
Forbid to do it in via bar menu and when validate new properties.
And also add a warning in the properties if this happens

![image](https://user-images.githubusercontent.com/7809481/148137759-6f236f2f-877c-4726-9533-df1ad9e13cee.png)

All the more that the via seems to be correctly drawn

**Comment by ubruhin** [comment]
I agree, this should not be possible :+1:
